# 30 practical data-cleaning questions

# 1. Load the CSV file using Pandas and display the first 10 rows.

In [1]:
import pandas as pd

df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\messy_customer_loan_dataset - messy_customer_loan_dataset.csv")
df.head()

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No
1,CUST100077,36,1048283,874,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792,48,11,0.558,Yes
2,CUST100317,55,1043481,661,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792,84,4,NaN,Yes
3,CUST101041,54,369591,722,Salaried,Graduate,Single,Kolkata,Premium,Home,908250,84,10,0.356,Yes
4,CUST101358,27,666989,727,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370,72,4,0.169,Yes

# 2. Display the number of rows and columns in the dataset.

In [2]:
df.shape

(1535, 15)

# 3. Display all column names and identify which column names have leading/trailing spaces.

In [3]:
df2 = df.columns
df2

Index(['Customer ID', 'Age', 'Annual Income', 'credit Score',
       'Employment-Type', 'Education  Level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'Loan Amount (INR)', 'tenure Months',
       'Monthly Visits', 'debt_to_income', 'Loan Approved?'],
      dtype='object')

# 4. Clean all column names by removing extra spaces and converting them into a consistent format such as snake_case.

In [4]:
df.columns = (df.columns.str.strip().str.replace(' ','_'))
df.columns

Index(['Customer_ID', 'Age', 'Annual_Income', 'credit_Score',
       'Employment-Type', 'Education__Level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'Loan_Amount_(INR)', 'tenure_Months',
       'Monthly_Visits', 'debt_to_income', 'Loan_Approved?'],
      dtype='object')

# 5. Check the data type of every column.

In [5]:
df.dtypes

Customer_ID          object
Age                  object
Annual_Income        object
credit_Score         object
Employment-Type      object
Education__Level     object
marital_status       object
city                 object
customer_segment     object
loan_type            object
Loan_Amount_(INR)    object
tenure_Months         int64
Monthly_Visits       object
debt_to_income       object
Loan_Approved?       object
dtype: object

# 6. Find the total number of missing values in each column.

In [6]:
df.isna().sum()

Customer_ID            0
Age                   71
Annual_Income         84
credit_Score          77
Employment-Type       60
Education__Level      46
marital_status         0
city                  52
customer_segment       0
loan_type              0
Loan_Amount_(INR)    102
tenure_Months          0
Monthly_Visits        55
debt_to_income        89
Loan_Approved?         0
dtype: int64

# 7. Find the percentage of missing values in each column.

In [7]:
missing_percentage = df.isnull().mean() * 100
missing_percentage

Customer_ID          0.000000
Age                  4.625407
Annual_Income        5.472313
credit_Score         5.016287
Employment-Type      3.908795
Education__Level     2.996743
marital_status       0.000000
city                 3.387622
customer_segment     0.000000
loan_type            0.000000
Loan_Amount_(INR)    6.644951
tenure_Months        0.000000
Monthly_Visits       3.583062
debt_to_income       5.798046
Loan_Approved?       0.000000
dtype: float64

# 8. Find all rows where Age is missing.

In [8]:
df['Age']= df['Age'].isnull().sum()
df['Age']

0       71
1       71
2       71
3       71
4       71
        ..
1530    71
1531    71
1532    71
1533    71
1534    71
Name: Age, Length: 1535, dtype: int64

# 9. Find all rows where Annual Income is missing.

In [9]:
df['Annual_Income'] = df['Annual_Income'].isnull().sum()
df['Annual_Income']

0       84
1       84
2       84
3       84
4       84
        ..
1530    84
1531    84
1532    84
1533    84
1534    84
Name: Annual_Income, Length: 1535, dtype: int64

# 10.Remove completely duplicate rows and report how many duplicate rows were removed.

In [10]:
df2 = df.drop_duplicates().isnull().sum()
df2

Customer_ID            0
Age                    0
Annual_Income          0
credit_Score          76
Employment-Type       59
Education__Level      45
marital_status         0
city                  52
customer_segment       0
loan_type              0
Loan_Amount_(INR)    100
tenure_Months          0
Monthly_Visits        53
debt_to_income        89
Loan_Approved?         0
dtype: int64

# 11.The Age column contains numbers as well as values like "unknown" and
# "twenty five". Clean this column and convert it into a proper numeric column.

In [11]:
import numpy as np

In [12]:
df['Age'] = pd.to_numeric(df['Age'],errors="coerce")
df['Age'] = df['Age'].fillna(df['Age'].median())
abs(df["Age"].unique())

array([71])

# 12.The Annual Income column contains values such as 650000 INR, ₹720000,
# 1.2L, and N/A. Clean the column and convert the valid values into numeric format.

In [13]:
df['Annual_Income'].unique()
df['Annual_Income']=df['Annual_Income'].astype(str).str.strip()

df['Annual_Income'] = (
    df['Annual_Income']
    .str.replace('INR', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)
df['Annual_Income'] = pd.to_numeric(
    df['Annual_Income'], errors='coerce'
)
df['Annual_Income'].isna().sum()

np.int64(0)

# 13.Clean the Credit Score column and identify values that cannot be converted into numbers.

In [14]:
df['credit_Score'].unique()
df['credit_Score'] = pd.to_numeric(df['credit_Score'],errors="coerce")
df['credit_Score'].isna().sum()

np.int64(97)

# 14.The Loan Amount column contains currency symbols, text, and numeric
# values. Remove the unwanted characters and convert it into numeric format.

In [15]:
df['Loan_Amount_(INR)'].unique()
df['Loan_Amount_(INR)'] = pd.to_numeric(df['Loan_Amount_(INR)'],errors="coerce")
df['Loan_Amount_(INR)'] = df['Loan_Amount_(INR)'].fillna(df['Loan_Amount_(INR)'].median())
df['Loan_Amount_(INR)'].isna().sum()

np.int64(0)

# 15.The Monthly Visits column contains values such as "five", "N/A", and "-".
# Convert valid values into numeric values and handle invalid values.

In [16]:
df['Monthly_Visits'].nunique()
df['Monthly_Visits'] = pd.to_numeric(df['Monthly_Visits'],errors="coerce")
df['Monthly_Visits'] = df['Monthly_Visits'].fillna(df['Monthly_Visits'].median())
df['Monthly_Visits'].unique()

array([  3.,  11.,   4.,  10.,   5.,   7.,   2.,   6.,   1.,   8.,   0.,
         9.,  12.,  -5.,  80.,  13., 150.,  15.])

# 16.Clean the Debt to Income column where some values are written like 35%
# and 0.4x. Convert the valid values into a consistent numeric format.

In [17]:
df['debt_to_income'].nunique()
df['debt_to_income'] = pd.to_numeric(df['debt_to_income'],errors="coerce")
df['debt_to_income'] = df['debt_to_income'].fillna(df['debt_to_income'].median())
abs(df['debt_to_income'].unique())

array([0.258, 0.558, 0.344, 0.356, 0.169, 0.46 , 0.323, 0.233, 0.375,
       0.394, 0.476, 0.487, 0.494, 0.364, 0.529, 0.564, 0.303, 0.386,
       0.177, 0.353, 0.657, 0.234, 0.195, 0.333, 0.485, 0.42 , 0.231,
       0.2  , 0.291, 0.366, 0.449, 0.397, 0.287, 0.508, 0.533, 1.2  ,
       0.112, 0.327, 0.348, 0.079, 0.328, 0.653, 0.228, 0.361, 0.164,
       0.538, 0.381, 0.274, 0.741, 0.357, 0.317, 0.02 , 0.419, 0.341,
       0.304, 0.3  , 0.32 , 0.555, 0.44 , 0.552, 0.259, 0.377, 0.331,
       0.083, 0.619, 0.418, 9.   , 0.617, 0.246, 0.238, 0.308, 0.645,
       0.723, 0.354, 0.682, 0.167, 0.457, 0.31 , 0.368, 0.181, 0.241,
       0.413, 0.048, 0.268, 0.441, 0.133, 0.365, 0.402, 0.276, 0.158,
       0.352, 0.553, 0.279, 0.722, 0.193, 0.102, 0.622, 3.5  , 0.629,
       0.416, 0.199, 0.513, 0.215, 0.334, 0.29 , 0.282, 0.608, 0.426,
       0.35 , 0.115, 0.343, 0.495, 0.444, 0.172, 0.596, 0.173, 0.2  ,
       0.252, 0.398, 0.399, 0.031, 0.313, 0.211, 0.236, 0.423, 0.424,
       0.292, 0.261, 0.183, 0.683, 0.285, 0.321, 0.4  , 0.445, 0.464,
       0.256, 0.165, 0.408, 0.237, 0.521, 0.094, 0.383, 0.157, 0.296,
       0.134, 0.182, 0.637, 0.483, 0.493, 0.455, 0.16 , 0.251, 0.213,
       0.288, 0.509, 0.107, 0.243, 0.422, 0.325, 0.224, 0.283, 0.36 ,
       0.401, 0.728, 0.492, 0.216, 0.209, 0.175, 0.545, 0.119, 0.139,
       0.524, 0.324, 0.373, 0.561, 0.219, 0.09 , 0.153, 0.459, 0.403,
       0.551, 0.454, 0.319, 0.514, 0.272, 0.411, 0.128, 0.125, 0.489,
       0.143, 0.523, 0.436, 0.269, 0.098, 0.548, 0.574, 0.472, 0.137,
       0.189, 0.567, 0.142, 0.446, 0.433, 0.388, 0.415, 0.254, 0.186,
       0.203, 0.477, 0.51 , 0.267, 0.166, 0.369, 0.121, 0.147, 0.271,
       0.469, 0.486, 0.473, 0.439, 0.748, 0.322, 0.136, 0.275, 0.295,
       0.212, 0.501, 0.382, 0.479, 0.065, 0.226, 0.385, 0.38 , 0.468,
       0.185, 0.318, 0.539, 0.5  , 0.421, 0.198, 0.248, 0.171, 0.289,
       0.431, 0.581, 0.478, 0.432, 0.335, 0.652, 0.097, 0.435, 0.376,
       0.355, 0.338, 0.222, 0.425, 0.427, 0.515, 0.417, 0.103, 0.404,
       0.559, 0.384, 0.14 , 0.18 , 0.488, 0.148, 0.161, 0.229, 0.249,
       0.387, 0.526, 0.371, 0.255, 0.096, 0.124, 0.178, 0.482, 0.311,
       0.544, 0.24 , 0.108, 0.264, 0.37 , 0.347, 0.309, 0.463, 0.168,
       0.461, 0.442, 0.541, 0.174, 0.221, 0.242, 0.475, 0.214, 0.598,
       0.247, 0.316, 0.208, 0.277, 0.499, 0.095, 0.342, 0.326, 0.346,
       0.45 , 0.456, 0.504, 0.606, 0.122, 0.345, 0.578, 0.336, 0.359,
       0.379, 0.263, 0.497, 0.298, 0.41 , 0.618, 0.281, 0.412, 0.438,
       0.306, 0.135, 0.041, 0.106, 0.126, 0.563, 0.414, 0.23 , 0.266,
       0.245, 0.315, 0.636, 0.407, 0.075, 0.577, 0.676, 0.244, 0.48 ,
       0.329, 0.13 , 0.101, 0.151, 0.196, 0.027, 0.297, 0.536, 0.588,
       0.54 , 0.374, 0.047, 0.584, 0.451, 0.556, 0.518, 0.613, 0.081,
       0.447, 0.078, 0.12 , 0.273, 0.191, 0.428, 0.305, 0.253, 0.349,
       0.638, 0.542, 0.159, 0.516, 0.39 , 0.307, 0.698, 0.507, 0.406,
       0.512, 0.755, 0.465, 0.474, 0.301, 0.063, 0.27 , 0.184, 0.074,
       0.572, 0.57 , 0.484, 0.481, 0.284, 0.294, 0.179, 0.064, 0.207,
       0.672, 0.491, 0.503, 0.114, 0.188, 0.197, 0.156, 0.076, 0.59 ,
       0.389, 0.458, 0.648, 0.144, 0.293, 0.217, 0.235, 0.05 , 0.395,
       0.68 , 0.066, 0.339, 0.032, 0.78 , 0.19 , 0.547, 0.55 , 0.466,
       0.227, 0.358, 0.362, 0.15 , 0.084, 0.53 , 0.257, 0.367, 0.64 ,
       0.363, 0.614, 0.405, 0.129, 0.34 , 0.739, 0.332, 0.141, 0.314,
       0.537, 0.434, 0.579, 0.43 , 0.452, 0.082, 0.735, 0.554, 0.517,
       0.665, 0.605, 0.239, 0.505, 0.26 , 0.639, 0.163, 0.351, 0.534,
       0.204, 0.532, 0.378, 0.74 , 0.206, 0.569, 0.149, 0.396, 0.49 ,
       0.462, 0.409, 0.146, 0.594, 0.123, 0.67 , 0.506, 0.771, 0.21 ,
       0.372, 0.104, 0.202, 0.176, 0.691, 0.58 , 0.582, 0.635, 0.674,
       0.22 , 0.117, 0.528, 0.688, 0.392, 0.429, 0.527, 0.393, 0.17 ,
       0.28 , 0.087, 0.437, 0.225, 0.597, 0.6  , 0.059, 0.549, 0.33 ,
       0.25 , 0.089, 0.522, 0.391, 0.724, 0.337, 0.633, 0.145, 0.223,
       0.496, 0.302, 0.023, 0.651, 0.628])

# 17.After cleaning the numerical columns, check which columns are still stored as object data type.

In [18]:
df.dtypes.value_counts()

object     8
float64    4
int64      3
Name: count, dtype: int64

# 18.Find all unique values in the Employment-Type column.

In [19]:
df['Employment-Type'].unique()

array(['Self-Employed', 'Contract', 'Salaried', 'SALARIED',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

# 19.Standardize the Employment-Type column so that values such as salaried,
# SALARIED, and Salaried become one consistent value.

In [7]:
import pandas as pd

df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\messy_customer_loan_dataset - messy_customer_loan_dataset.csv")
df.head(1)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No

In [16]:
df['Employment-Type'] = df['Employment-Type'].replace({'self-employedd':'Self-Employed',
                                                       'Self employed':'Self-Employed',
                                                       'Salaried':'SALARIED',
                                                        'salaried':'SALARIED',
                                                       'Unknown':'nan'
})
df['Employment-Type'].unique()

array(['Self-Employed', 'Contract', 'SALARIED', 'Business', nan, 'nan',
       'self-employed'], dtype=object)

# 20.Clean the Education Level column and make values such as graduate,
# GRADUATE, and Graduate consistent.

In [10]:
df.columns = (df.columns.str.strip().str.replace(' ','_'))
df.columns

Index(['Customer_ID', 'Age', 'Annual_Income', 'credit_Score',
       'Employment-Type', 'Education__Level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'Loan_Amount_(INR)', 'tenure_Months',
       'Monthly_Visits', 'debt_to_income', 'Loan_Approved?'],
      dtype='object')

In [11]:
df.columns

Index(['Customer_ID', 'Age', 'Annual_Income', 'credit_Score',
       'Employment-Type', 'Education__Level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'Loan_Amount_(INR)', 'tenure_Months',
       'Monthly_Visits', 'debt_to_income', 'Loan_Approved?'],
      dtype='object')

In [12]:
df['Education__Level'].unique()

array(['12th', 'Graduate', 'Postgraduate', 'Diploma', nan,
       'Post Graduate', 'Other', 'GRADUATE', 'postgraduate', 'graduate'],
      dtype=object)

In [14]:
df['Education__Level']= df['Education__Level'].replace({'graduate':'GRADUATE',
                                                        'graduate':'GRADUATE',
                                                        'Postgraduate':'Postgraduate',
                                                        'Post Graduate':'Postgraduate'
})
df['Education__Level'].unique()

array(['12th', 'Graduate', 'Postgraduate', 'Diploma', nan, 'Other',
       'GRADUATE', 'postgraduate'], dtype=object)

# 21.Clean the City column. Identify incorrect or inconsistent values such as
# hyderbad, Hyd, Bangalore, and Bengaluru.

In [17]:
df['city'].unique()

array(['Mumbai', 'Jaipur', 'Kolkata', 'Hyderabad', 'Chennai', 'Bengaluru',
       nan, 'Delhi', 'Pune', 'MUMBAI', 'Hyd', 'mumbai', 'Bangalore',
       'hyderbad'], dtype=object)

In [19]:
df['city']= df['city'].replace({'mumbai':'MUMBAI',
                                'hyderbad':'Hyderabad',
                                'Hyd':'Hyderabad',
                                'Bengaluru':'Bangalore',
                                'mumbai':'MUMBAI',
                                'Mumbai':'MUMBAI'
})
df['city'].unique()

array(['MUMBAI', 'Jaipur', 'Kolkata', 'Hyderabad', 'Chennai', 'Bangalore',
       nan, 'Delhi', 'Pune'], dtype=object)

# 22.Find all unique values in the Customer Segment column and identify invalid categories.

In [23]:
df['customer_segment'].unique()

array(['Mass', 'PREMIUM', 'Affluent', 'Premium', 'SME', 'premium',
       'unknown', 'High Value', 'mass'], dtype=object)

In [26]:
df['customer_segment']= df['customer_segment'].replace({'mass':'Mass',
                                'premium':'PREMIUM',
                                'Premium':'PREMIUM'
                                
                                
})
df['customer_segment'].unique()

array(['Mass', 'PREMIUM', 'Affluent', 'SME', 'unknown', 'High Value'],
      dtype=object)

# 23.Clean the Loan Type column so that values such as personal, PERSONAL, and personal loan are standardized.

In [20]:
df['loan_type'].unique()

array(['Education', 'Auto', 'Home', 'Personal', 'Business',
       'personal loan', 'Home Loan', 'PERSONAL', 'auto', 'Unknown'],
      dtype=object)

In [22]:
df['loan_type']= df['loan_type'].replace({'auto':'Auto',
                                'Personal':'PERSONAL',
                                'Home':'Home Loan',
                                'personal loan':'PERSONAL',
                                
})
df['loan_type'].unique()

array(['Education', 'Auto', 'Home Loan', 'PERSONAL', 'Business',
       'Unknown'], dtype=object)

# 24.Clean the Loan Approved column where values include Yes, yes, Y, 1, No,
# NO, N, and 0. Convert them into only Yes/No.

In [27]:
df['Loan_Approved?'].unique()

array(['No', 'Yes', '0', 'yes', 'N', 'pending', '1', 'approved', 'NO',
       'Y'], dtype=object)

In [29]:
df['Loan_Approved?'].replace({"N":"NO",
                                "yes":"Yes",
                                "Y":"Yes",
                                "No":"NO"
})
df['Loan_Approved?'].unique()

array(['No', 'Yes', '0', 'yes', 'N', 'pending', '1', 'approved', 'NO',
       'Y'], dtype=object)

# 25.Check the Age column and identify unrealistic ages such as negative ages or ages above 100.

In [34]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

df[(df['Age'] < 0) | (df['Age'] > 100)]

,Customer_ID,Age,Annual_Income,credit_Score,Employment-Type,Education__Level,marital_status,city,customer_segment,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits,debt_to_income,Loan_Approved?
143,CUST101478,105.0,654405,705,Self-Employed,Other,Single,Pune,Affluent,Business,307579,12,9,0.398,Yes
264,CUST100715,105.0,728296,668,SALARIED,12th,Married,Jaipur,SME,PERSONAL,317698,48,4,0.186,Yes
308,CUST100846,105.0,479269,715,Self-Employed,Graduate,Married,Pune,Affluent,Home Loan,1894157,60,1,0.38,Yes
383,CUST101107,-3.0,982428,NaN,Business,Graduate,Married,MUMBAI,SME,Auto,NaN,72,1,0.249,Yes
581,CUST100261,130.0,811910,828,Self-Employed,NaN,Married,Chennai,Affluent,PERSONAL,493393,60,4,0.426,Yes
689,CUST100639,-3.0,533794,694,SALARIED,GRADUATE,Single,Hyderabad,Affluent,Home Loan,NaN,120,6,0.256,Yes
892,CUST101177,-3.0,25000000,659,Business,NaN,Single,Delhi,Affluent,Auto,623885,120,5,0.257,Yes
923,CUST100556,105.0,657328,878,Business,Diploma,Married,MUMBAI,High Value,Education,694953,24,3,0.261,Yes
1039,CUST101156,-3.0,270249,677,Contract,Other,Married,Chennai,Mass,Education,220207,120,6,NaN,No
1070,CUST100849,-3.0,NaN,844,Business,Diploma,Married,Bangalore,PREMIUM,Business,3599535,48,8,0.639,Yes
1399,CUST101411,105.0,681307,760,Contract,Graduate,Single,Kolkata,Mass,Home Loan,237072,36,5,0.298,Yes
1465,CUST101105,105.0,426130,771,Business,Graduate,Married,Chennai,Mass,Business,261086,72,2,NaN,Yes

# 26.Check the Credit Score column and identify values outside the valid credit- score range.

In [44]:
df['credit_Score'] = pd.to_numeric(df['credit_Score'], errors='coerce')

df[(df['credit_Score'] < 350) | (df['credit_Score'] > 850)]
df['credit_Score']

0       698.0
1       874.0
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531      0.0
1532    686.0
1533    720.0
1534    731.0
Name: credit_Score, Length: 1535, dtype: float64

# 27.Detect outliers in Annual Income using the IQR method.

In [48]:
df['Annual_Income'] = pd.to_numeric(df['Annual_Income'], errors='coerce')


Q1 =df['Annual_Income'].quantile(0.25)
Q3 =df['Annual_Income'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df['Annual_Income'] < lower_limit) |
    (df['Annual_Income'] > upper_limit)
]
outliers

,Customer_ID,Age,Annual_Income,credit_Score,Employment-Type,Education__Level,marital_status,city,customer_segment,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits,debt_to_income,Loan_Approved?
14,CUST101158,60.0,1548824.0,698.0,Contract,Graduate,Married,Pune,SME,Home Loan,333121.0,24,10,0.529,No
61,CUST100757,55.0,1777657.0,666.0,Contract,Postgraduate,Single,Hyderabad,PREMIUM,Education,900253.0,72,3,0.304,Yes
74,CUST100238,41.0,1907548.0,678.0,Business,Graduate,Single,MUMBAI,Mass,Business,242378.0,72,0,NaN,Yes
184,CUST100692,NaN,1895511.0,832.0,Self-Employed,Graduate,Married,Jaipur,SME,PERSONAL,518143.0,48,2,0.637,No
208,CUST100616,51.0,1586888.0,708.0,Contract,12th,Married,Delhi,Mass,PERSONAL,461215.0,84,NaN,0.401,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1409,CUST100407,41.0,1521141.0,799.0,Self-Employed,Graduate,Single,Kolkata,Affluent,Auto,573489.0,120,2,0.078,Yes
1464,CUST101412,47.0,1996474.0,789.0,Contract,Postgraduate,Married,Kolkata,High Value,PERSONAL,460487.0,72,4,0.157,Yes
1466,CUST100206,33.0,1604257.0,785.0,Contract,12th,Single,MUMBAI,Affluent,Business,NaN,24,3,0.355,No
1467,CUST100035,62.0,1531271.0,779.0,Business,Postgraduate,Single,Hyderabad,Mass,PERSONAL,327941.0,24,4,0.179,Yes
1515,CUST100344,45.0,80000000.0,819.0,Self-Employed,Postgraduate,Single,MUMBAI,Mass,PERSONAL,636933.0,12,6,0.384,Yes

# 28.Detect outliers in Loan Amount using the IQR method.

In [47]:
df['Loan_Amount_(INR)'] =pd.to_numeric(df['Loan_Amount_(INR)'],errors="coerce")

Q1 = df['Loan_Amount_(INR)'].quantile(0.25)
Q3 = df['Loan_Amount_(INR)'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df['Annual_Income'] < lower_limit) |
    (df['Annual_Income'] > upper_limit)
]
outliers

,Customer_ID,Age,Annual_Income,credit_Score,Employment-Type,Education__Level,marital_status,city,customer_segment,loan_type,Loan_Amount_(INR),tenure_Months,Monthly_Visits,debt_to_income,Loan_Approved?
14,CUST101158,60.0,1548824.0,698.0,Contract,Graduate,Married,Pune,SME,Home Loan,333121.0,24,10,0.529,No
18,CUST100050,57.0,1457160.0,687.0,Business,12th,Divorced,Kolkata,Affluent,Home Loan,258267.0,12,4,NaN,Yes
19,CUST100241,27.0,1412437.0,637.0,Business,Postgraduate,Married,MUMBAI,Affluent,Education,752049.0,48,4,0.386,Yes
61,CUST100757,55.0,1777657.0,666.0,Contract,Postgraduate,Single,Hyderabad,PREMIUM,Education,900253.0,72,3,0.304,Yes
74,CUST100238,41.0,1907548.0,678.0,Business,Graduate,Single,MUMBAI,Mass,Business,242378.0,72,0,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1466,CUST100206,33.0,1604257.0,785.0,Contract,12th,Single,MUMBAI,Affluent,Business,NaN,24,3,0.355,No
1467,CUST100035,62.0,1531271.0,779.0,Business,Postgraduate,Single,Hyderabad,Mass,PERSONAL,327941.0,24,4,0.179,Yes
1511,CUST101216,26.0,1403890.0,NaN,NaN,Graduate,Single,Pune,Mass,Home Loan,328004.0,72,6,0.05,approved
1515,CUST100344,45.0,80000000.0,819.0,Self-Employed,Postgraduate,Single,MUMBAI,Mass,PERSONAL,636933.0,12,6,0.384,Yes
1531,CUST101295,65.0,1394481.0,0.0,Self-Employed,12th,Single,Jaipur,Mass,PERSONAL,222828.0,120,8,0.344,Yes

# 29.Check the Debt to Income column and identify impossible values such as
# negative values or values greater than 1.

In [53]:
df['debt_to_income'] = pd.to_numeric(df['debt_to_income'], errors='coerce')
df[(df['debt_to_income'] < 0) | (df['debt_to_income'] > 1)]

((df['debt_to_income'] < 0) | (df['debt_to_income'] > 1)).sum()

np.int64(18)

In [ ]:
#