 # EV Resale Price Regression

In [3]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\EV_Resale_Price_Regression - EV_Resale_Price_Regression.csv")
df.head(7)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249
3,EV-20935,2025-01-04,2022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422
4,EV-20827,2025-01-05,2024,GreenDrive,Sedan,53.0,92.0,264.0,28548.0000,6.1,No,1,Pune,Complete,1642232
5,EV-20547,2025-01-06,2022,Atheron,Crossover,44.1,89.6,407.0,37590.0000,5.5,No,4,Mumbai,Complete,1533320
6,EV-20961,2025-01-07,2017,Atheron,Sedan,34.9,89.9,468.0,11615.0000,5.0,No,1,Mumbai,Complete,1605157

### 1. Data Quality Audit
### Perform a complete audit of the dataset:
### • shape
### • datatypes
### • missing values
### • duplicate records
### • unique vehicle IDs
### • categorical distributions

In [10]:
df.shape

(1000, 15)

In [11]:
df.dtypes

vehicle_id               object
listing_date             object
manufacture_year          int64
brand                    object
vehicle_type             object
battery_capacity_kwh    float64
battery_health_pct      float64
range_km                float64
km_driven               float64
charging_time_hr        float64
fast_charging            object
owner_count               int64
city                     object
service_history          object
resale_price              int64
dtype: object

In [12]:
df.isna().sum()

vehicle_id               0
listing_date             0
manufacture_year         0
brand                    0
vehicle_type             0
battery_capacity_kwh    25
battery_health_pct      30
range_km                20
km_driven                0
charging_time_hr        24
fast_charging            0
owner_count              0
city                     0
service_history         30
resale_price             0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['vehicle_id'].unique()

In [21]:
df['vehicle_type'].value_counts()

vehicle_type
SUV          265
Hatchback    251
Crossover    244
Sedan        240
Name: count, dtype: int64

### 2. Duplicate Vehicle Investigation
### vehicle_id is expected to uniquely identify a vehicle.
### Determine:
### • how many duplicated vehicle_id values exist
### • which vehicle IDs are duplicated
### • how many records are affected
### Then decide how you would handle these records without blindly using drop_duplicates().

In [32]:
# 1. Number of duplicated Vehicle_ID values
duplicate_ids = df['vehicle_id'].duplicated(keep=False)

print("Number of duplicated Vehicle_ID values:",
      df.loc[duplicate_ids, 'vehicle_id'].nunique())


# 2. Which Vehicle_IDs are duplicated
print("\nDuplicated Vehicle_IDs:")
print(df.loc[duplicate_ids, 'vehicle_id'].unique())


# 3. How many records are affected
print("\nNumber of affected records:",
      duplicate_ids.sum())


# 4. Display all records having duplicated Vehicle_IDs
print("\nDuplicated Vehicle Records:")
df.loc[duplicate_ids].sort_values('vehicle_id')

Number of duplicated Vehicle_ID values: 6

Duplicated Vehicle_IDs:
['EV-20515' 'EV-20653' 'EV-20011' 'EV-20544' 'EV-20193' 'EV-20279']

Number of affected records: 12

Duplicated Vehicle Records:

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
119,EV-20011,2025-04-30,2016,Nexora,Sedan,57.9,99.5,NaN,40831.0,8.4,Yes,4,Mumbai,Complete,1591429
852,EV-20011,2027-05-03,2016,Nexora,Sedan,57.9,99.5,NaN,40831.0,8.4,Yes,4,Mumbai,Complete,1591429
655,EV-20193,2026-10-18,2023,Atheron,Crossover,31.3,97.2,285.0,33740.0,8.1,Yes,4,Chennai,Complete,1444991
797,EV-20193,2027-03-09,2023,Atheron,Crossover,31.3,97.2,285.0,33740.0,8.1,Yes,4,Chennai,Complete,1444991
816,EV-20279,2027-03-28,2019,E-Motion,SUV,65.6,87.1,381.0,116102.0,6.8,No,2,Bengaluru,Complete,1395622
857,EV-20279,2027-05-08,2019,E-Motion,SUV,65.6,87.1,381.0,116102.0,6.8,No,2,Bengaluru,Complete,1395622
72,EV-20515,2025-03-14,2016,GreenDrive,Hatchback,61.6,100.0,210.0,37482.0,7.0,Yes,1,Mumbai,Complete,1492498
621,EV-20515,2026-09-14,2016,GreenDrive,Hatchback,61.6,100.0,210.0,37482.0,7.0,Yes,1,Mumbai,Complete,1492498
133,EV-20544,2025-05-14,2024,E-Motion,Sedan,38.0,93.9,511.0,67782.0,3.1,Yes,2,Chennai,Complete,1604620
280,EV-20544,2025-10-08,2024,E-Motion,Sedan,38.0,93.9,511.0,67782.0,3.1,Yes,2,Chennai,Complete,1604620
81,EV-20653,2025-03-23,2019,Atheron,Crossover,61.4,92.3,398.0,72412.0,10.6,No,4,Chennai,Complete,1267473
989,EV-20653,2027-09-17,2019,Atheron,Crossover,61.4,92.3,398.0,72412.0,10.6,No,4,Chennai,Complete,1267473

### . Date Conversion & Validation
### onvert listing_date into a proper datetime column.
### hen investigate:
###  earliest listing date
###  latest listing date
###  invalid/missing dates
###  whether the date column is suitable for feature engineering.

In [33]:
#  earliest listing date:
df2['listing_date'] = pd.to_datetime(df['listing_date'],errors='coerce')
df2

0                                                           False
1                                                           False
2                                                           False
3                                                           False
4                                                           False
                                      ...
996                                                         False
997                                                         False
998                                                         False
999                                                         False
listing_date    0     2025-01-01
1     2025-01-02
2     2025-0...
Name: vehicle_id, Length: 1001, dtype: object

In [34]:
df2['listing_date'].min()
df2

0                                                           False
1                                                           False
2                                                           False
3                                                           False
4                                                           False
                                      ...
996                                                         False
997                                                         False
998                                                         False
999                                                         False
listing_date    0     2025-01-01
1     2025-01-02
2     2025-0...
Name: vehicle_id, Length: 1001, dtype: object

In [35]:
df2['listing_date'].max()
df2

0                                                           False
1                                                           False
2                                                           False
3                                                           False
4                                                           False
                                      ...
996                                                         False
997                                                         False
998                                                         False
999                                                         False
listing_date    0     2025-01-01
1     2025-01-02
2     2025-0...
Name: vehicle_id, Length: 1001, dtype: object

In [37]:
# invalid/missing dates
df2 = df['listing_date'].isna().sum()
df2

np.int64(0)

In [39]:
df2 = df.dtypes
df2

vehicle_id               object
listing_date             object
manufacture_year          int64
brand                    object
vehicle_type             object
battery_capacity_kwh    float64
battery_health_pct      float64
range_km                float64
km_driven               float64
charging_time_hr        float64
fast_charging            object
owner_count               int64
city                     object
service_history          object
resale_price              int64
dtype: object

### 4. Vehicle Age Feature
### Create vehicle_age using:
### listing year − manufacture year
### Then identify whether any vehicle has:
### • age < 0
### • age = 0
### • unusually high age

In [48]:
df2 = df['manufacture_year']
df2

0      2021
1      2025
2      2019
3      2022
4      2024
       ...
995    2017
996    2020
997    2025
998    2019
999    2019
Name: manufacture_year, Length: 1000, dtype: int64

In [50]:
df2=df['manufacture_year'] = pd.to_datetime(df['manufacture_year'],errors='coerce')
df2

0     1970-01-01 00:00:00.000002021
1     1970-01-01 00:00:00.000002025
2     1970-01-01 00:00:00.000002019
3     1970-01-01 00:00:00.000002022
4     1970-01-01 00:00:00.000002024
                   ...
995   1970-01-01 00:00:00.000002017
996   1970-01-01 00:00:00.000002020
997   1970-01-01 00:00:00.000002025
998   1970-01-01 00:00:00.000002019
999   1970-01-01 00:00:00.000002019
Name: manufacture_year, Length: 1000, dtype: datetime64[ns]

In [51]:
df2 = df['manufacture_year'].dt.year
df2

0      1970
1      1970
2      1970
3      1970
4      1970
       ...
995    1970
996    1970
997    1970
998    1970
999    1970
Name: manufacture_year, Length: 1000, dtype: int32

## 5. Battery Data Imputation
## The following columns contain missing values:
## battery_capacity_kwh, battery_health_pct, range_km, charging_time_hr
## Develop an appropriate missing-value strategy for each column.
## Do not automatically use the same statistic for every column.

In [53]:
df2 = df[['battery_capacity_kwh','battery_health_pct','charging_time_hr']].isnull().sum()
df2

battery_capacity_kwh    25
battery_health_pct      30
charging_time_hr        24
dtype: int64

In [57]:
df2=df['battery_capacity_kwh'].describe()
df2

count    975.000000
mean      58.288755
std       14.199822
min       25.000000
25%       48.700000
50%       58.200000
75%       67.700000
max      110.405980
Name: battery_capacity_kwh, dtype: float64

In [58]:
df2=df['battery_capacity_kwh'].median()
df2

58.2

In [59]:
df2=df['battery_capacity_kwh'] = df['battery_capacity_kwh'].fillna(
    df['battery_capacity_kwh'].median()
)
df2

0      46.9
1      80.6
2      53.9
3      60.1
4      53.0
       ...
995    37.9
996    67.5
997    91.1
998    76.8
999    63.6
Name: battery_capacity_kwh, Length: 1000, dtype: float64

## 6. Battery Health Outlier Investigation
## Analyze battery_health_pct.
## Identify:
## • values below a reasonable minimum
## • values above 100
## • extreme observations
## Then decide whether to remove, cap, or retain suspicious values.

In [64]:
df2 = df['battery_health_pct'].describe()
df2

count    970.000000
mean      91.221546
std        4.835603
min       75.800000
25%       87.900000
50%       91.200000
75%       94.600000
max      100.000000
Name: battery_health_pct, dtype: float64

In [65]:
df2 = df['battery_health_pct'].min()
df2

75.8

In [66]:
df2 = df['battery_health_pct'].max()
df2

100.0

In [69]:
df1 = df['battery_health_pct'].quantile(0.25)
df2 = df['battery_health_pct'].quantile(0.75)
print(df1)
print(df2)

87.9
94.6

In [70]:
df2=df['battery_health_pct'] = df['battery_health_pct'].clip(0, 100)
df2

0      89.6
1      99.5
2      91.2
3      89.3
4      92.0
       ...
995    89.9
996    99.9
997    81.8
998    98.6
999    88.2
Name: battery_health_pct, Length: 1000, dtype: float64

## 7. Range vs Battery Capacity
## Create range_per_kwh using:
## range_km / battery_capacity_kwh
## Identify vehicles with unusually low or high efficiency.

In [71]:
df.head(2)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,1970-01-01 00:00:00.000002021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836
1,EV-20530,2025-01-02,1970-01-01 00:00:00.000002025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760

In [75]:
df2 = df['range_km'].describe()
df2

count    980.000000
mean     370.018367
std       84.986135
min      150.000000
25%      310.750000
50%      371.000000
75%      427.250000
max      630.000000
Name: range_km, dtype: float64

In [76]:
df['range_per_kwh'] = df['range_km'] / df['battery_capacity_kwh']
df

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price,range_per_kwh
0,EV-20170,2025-01-01,1970-01-01 00:00:00.000002021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836,6.673774
1,EV-20530,2025-01-02,1970-01-01 00:00:00.000002025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760,6.736973
2,EV-20654,2025-01-03,1970-01-01 00:00:00.000002019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249,NaN
3,EV-20935,2025-01-04,1970-01-01 00:00:00.000002022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422,8.785358
4,EV-20827,2025-01-05,1970-01-01 00:00:00.000002024,GreenDrive,Sedan,53.0,92.0,264.0,28548.0000,6.1,No,1,Pune,Complete,1642232,4.981132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,EV-20357,2027-09-23,1970-01-01 00:00:00.000002017,E-Motion,Sedan,37.9,89.9,333.0,61861.0000,3.0,No,1,Bengaluru,Complete,1338124,8.786280
996,EV-20756,2027-09-24,1970-01-01 00:00:00.000002020,Atheron,Hatchback,67.5,99.9,290.0,55605.0000,9.2,Yes,1,Bengaluru,Complete,1624596,4.296296
997,EV-20984,2027-09-25,1970-01-01 00:00:00.000002025,Atheron,Crossover,91.1,81.8,434.0,23708.0000,2.0,No,1,Delhi,Partial,1958519,4.763996
998,EV-20410,2027-09-26,1970-01-01 00:00:00.000002019,GreenDrive,Sedan,76.8,98.6,264.0,39435.0000,2.8,Yes,1,Chennai,Complete,1724555,3.437500
999,EV-20168,2027-09-27,1970-01-01 00:00:00.000002019,Voltix,Crossover,63.6,88.2,150.0,103173.0000,NaN,No,3,Pune,Complete,1232571,2.358491

In [ ]:
# Higher range_per_kwh → better efficiency
# Lower range_per_kwh → lower efficiency

# IQR means Interquartile Range. It tells us how spread out the middle 50% of the data is.
# Why do we use IQR?

# Mainly to identify unusually low or high values (outliers).

In [79]:
Q1 = df['range_per_kwh'].quantile(0.25)
Q3 = df['range_per_kwh'].quantile(0.75)

IQR = Q3 - Q1

In [80]:
lower = Q1 - 1.5 * IQR  # interquartile Range 
upper = Q3 + 1.5 * IQR

In [81]:
df[
    (df['range_per_kwh'] < lower) |
    (df['range_per_kwh'] > upper)
]
df

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price,range_per_kwh
0,EV-20170,2025-01-01,1970-01-01 00:00:00.000002021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836,6.673774
1,EV-20530,2025-01-02,1970-01-01 00:00:00.000002025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760,6.736973
2,EV-20654,2025-01-03,1970-01-01 00:00:00.000002019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249,NaN
3,EV-20935,2025-01-04,1970-01-01 00:00:00.000002022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422,8.785358
4,EV-20827,2025-01-05,1970-01-01 00:00:00.000002024,GreenDrive,Sedan,53.0,92.0,264.0,28548.0000,6.1,No,1,Pune,Complete,1642232,4.981132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,EV-20357,2027-09-23,1970-01-01 00:00:00.000002017,E-Motion,Sedan,37.9,89.9,333.0,61861.0000,3.0,No,1,Bengaluru,Complete,1338124,8.786280
996,EV-20756,2027-09-24,1970-01-01 00:00:00.000002020,Atheron,Hatchback,67.5,99.9,290.0,55605.0000,9.2,Yes,1,Bengaluru,Complete,1624596,4.296296
997,EV-20984,2027-09-25,1970-01-01 00:00:00.000002025,Atheron,Crossover,91.1,81.8,434.0,23708.0000,2.0,No,1,Delhi,Partial,1958519,4.763996
998,EV-20410,2027-09-26,1970-01-01 00:00:00.000002019,GreenDrive,Sedan,76.8,98.6,264.0,39435.0000,2.8,Yes,1,Chennai,Complete,1724555,3.437500
999,EV-20168,2027-09-27,1970-01-01 00:00:00.000002019,Voltix,Crossover,63.6,88.2,150.0,103173.0000,NaN,No,3,Pune,Complete,1232571,2.358491

## 8. Driving Intensity Feature
## Create km_per_year using:
## km_driven / vehicle_age
## Handle the special case where vehicle_age = 0.
## Identify unusually high annual driving.

In [2]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\MY PC\\Downloads\\EV_Resale_Price_Regression - EV_Resale_Price_Regression.csv")
df.head(2)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760

In [8]:
# so vehicle age missing create it
df['listing_date'] = pd.to_datetime(df['listing_date'], errors='coerce')
df.head(4)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249
3,EV-20935,2025-01-04,2022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422

In [13]:
df.columns

Index(['vehicle_id', 'listing_date', 'manufacture_year', 'brand',
       'vehicle_type', 'battery_capacity_kwh', 'battery_health_pct',
       'range_km', 'km_driven', 'charging_time_hr', 'fast_charging',
       'owner_count', 'city', 'service_history', 'resale_price'],
      dtype='object')

In [14]:
df['vehicle_age'] = 2026 - df['manufacture_year']

In [17]:
# Create km_per_year
import numpy as np
df['km_per_year'] = df['km_driven'] / df['vehicle_age'].replace(0, np.nan)
df.head(2)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price,vehicle_age,km_per_year
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836,5,5690.8000
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760,1,183935.8448

In [19]:
df[['manufacture_year', 'vehicle_age', 'km_driven', 'km_per_year']]
df.head(3)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price,vehicle_age,km_per_year
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836,5,5690.800000
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760,1,183935.844800
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249,7,1714.714286

In [20]:
Q1 = df['km_per_year'].quantile(0.25)
Q3 = df['km_per_year'].quantile(0.75)

IQR = Q3 - Q1

upper_limit = Q3 + 1.5 * IQR 

high_driving = df[df['km_per_year'] > upper_limit]

high_driving[['vehicle_id', 'km_driven', 'vehicle_age', 'km_per_year']]

    vehicle_id    km_driven  vehicle_age  km_per_year
1     EV-20530  183935.8448            1  183935.8448
8     EV-20708  128031.0000            1  128031.0000
9     EV-20059   55670.0000            1   55670.0000
12    EV-20381   46088.0000            1   46088.0000
19    EV-20301   54736.0000            1   54736.0000
..         ...          ...          ...          ...
940   EV-20010   38714.0000            1   38714.0000
956   EV-20762   54418.0000            1   54418.0000
980   EV-20485  169204.0000            4   42301.0000
983   EV-20062  146622.0000            2   73311.0000
984   EV-20438   69012.0000            1   69012.0000

[91 rows x 4 columns]

## 9. Charging Efficiency
## Create charging_efficiency using:
## range_km / charging_time_hr

In [23]:
df['charging_efficiency'] = (
    df['range_km'] / df['charging_time_hr'].replace(0, np.nan)
)
# display
df[['range_km', 'charging_time_hr', 'charging_efficiency']]

     range_km  charging_time_hr  charging_efficiency
0       313.0              10.0            31.300000
1       543.0               7.1            76.478873
2         NaN               3.6                  NaN
3       528.0               7.8            67.692308
4       264.0               6.1            43.278689
..        ...               ...                  ...
995     333.0               3.0           111.000000
996     290.0               9.2            31.521739
997     434.0               2.0           217.000000
998     264.0               2.8            94.285714
999     150.0               NaN                  NaN

[1000 rows x 3 columns]

In [24]:
df['charging_efficiency'].isna().sum()

np.int64(44)

In [25]:
df[['range_km', 'charging_time_hr', 'charging_efficiency']].isna().sum()

range_km               20
charging_time_hr       24
charging_efficiency    44
dtype: int64

In [26]:
Q1 = df['charging_efficiency'].quantile(0.25)
Q3 = df['charging_efficiency'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

extreme_values = df[
    (df['charging_efficiency'] < lower_limit) |
    (df['charging_efficiency'] > upper_limit)
]
extreme_values[['vehicle_id', 'range_km','charging_time_hr', 'charging_efficiency']]

    vehicle_id  range_km  charging_time_hr  charging_efficiency
27    EV-20085     424.0               2.9           146.206897
133   EV-20544     511.0               3.1           164.838710
147   EV-20420     439.0               2.5           175.600000
166   EV-20786     560.0               2.7           207.407407
171   EV-20655     339.0               2.0           169.500000
185   EV-20355     460.0               3.5           131.428571
243   EV-20339     447.0               3.3           135.454545
267   EV-20551     366.0               2.3           159.130435
280   EV-20544     511.0               3.1           164.838710
327   EV-20871     434.0               2.6           166.923077
334   EV-20727     537.0               3.6           149.166667
365   EV-20516     347.0               2.2           157.727273
374   EV-20484     407.0               2.8           145.357143
397   EV-20307     461.0               3.6           128.055556
445   EV-20682     565.0               3.9           144.871795
466   EV-20151     563.0               3.3           170.606061
496   EV-20650     487.0               2.7           180.370370
571   EV-20776     509.0               3.2           159.062500
591   EV-20894     514.0               3.4           151.176471
597   EV-20173     459.0               2.0           229.500000
618   EV-20479     569.0               3.9           145.897436
640   EV-20590     483.0               2.1           230.000000
643   EV-20808     428.0               3.0           142.666667
688   EV-20742     485.0               3.5           138.571429
709   EV-20755     483.0               3.0           161.000000
742   EV-20714     334.0               2.0           167.000000
747   EV-20504     294.0               2.2           133.636364
763   EV-20649     522.0               2.9           180.000000
765   EV-20422     497.0               3.6           138.055556
766   EV-20005     452.0               2.2           205.454545
767   EV-20457     516.0               3.2           161.250000
795   EV-20261     382.0               2.0           191.000000
809   EV-20345     275.0               2.0           137.500000
811   EV-20812     522.0               4.0           130.500000
826   EV-20475     501.0               3.3           151.818182
850   EV-20826     365.0               2.6           140.384615
892   EV-20731     539.0               3.9           138.205128
899   EV-20046     367.0               2.0           183.500000
912   EV-20759     432.0               3.1           139.354839
961   EV-20512     454.0               3.5           129.714286
983   EV-20062     474.0               3.2           148.125000
985   EV-20299     460.0               3.2           143.750000
986   EV-20525     397.0               2.1           189.047619
997   EV-20984     434.0               2.0           217.000000

## 10. Ownership Analysis
## Analyze owner_count.
## Determine:
## • frequency of each ownership level
## • whether any values are invalid
## • whether owner count should be treated as numerical or categorical for regression.

In [28]:
# Ownership Analysis:
df['owner_count'].value_counts().sort_index()
df

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price,vehicle_age,km_per_year,charging_efficiency
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836,5,5690.800000,31.300000
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760,1,183935.844800,76.478873
2,EV-20654,2025-01-03,2019,Nexora,Crossover,53.9,91.2,NaN,12003.0000,3.6,Yes,1,Chennai,Complete,1830249,7,1714.714286,NaN
3,EV-20935,2025-01-04,2022,GreenDrive,Hatchback,60.1,89.3,528.0,13623.0000,7.8,Yes,2,Delhi,Complete,1726422,4,3405.750000,67.692308
4,EV-20827,2025-01-05,2024,GreenDrive,Sedan,53.0,92.0,264.0,28548.0000,6.1,No,1,Pune,Complete,1642232,2,14274.000000,43.278689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,EV-20357,2027-09-23,2017,E-Motion,Sedan,37.9,89.9,333.0,61861.0000,3.0,No,1,Bengaluru,Complete,1338124,9,6873.444444,111.000000
996,EV-20756,2027-09-24,2020,Atheron,Hatchback,67.5,99.9,290.0,55605.0000,9.2,Yes,1,Bengaluru,Complete,1624596,6,9267.500000,31.521739
997,EV-20984,2027-09-25,2025,Atheron,Crossover,91.1,81.8,434.0,23708.0000,2.0,No,1,Delhi,Partial,1958519,1,23708.000000,217.000000
998,EV-20410,2027-09-26,2019,GreenDrive,Sedan,76.8,98.6,264.0,39435.0000,2.8,Yes,1,Chennai,Complete,1724555,7,5633.571429,94.285714
999,EV-20168,2027-09-27,2019,Voltix,Crossover,63.6,88.2,150.0,103173.0000,NaN,No,3,Pune,Complete,1232571,7,14739.000000,NaN

In [29]:
# Missing values:
print("Missing values:", df['owner_count'].isna().sum())

# Unique values:
print("Unique values:", sorted(df['owner_count'].dropna().unique()))

# Invalid values:
invalid_owner = df[
    (df['owner_count'].isna()) |
    (df['owner_count'] <= 0) |
    (df['owner_count'] % 1 != 0)
]
invalid_owner[['vehicle_id', 'owner_count']]

Missing values: 0
Unique values: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

Empty DataFrame
Columns: [vehicle_id, owner_count]
Index: []

## 11. Categorical Data Audit
## Analyze: brand, vehicle_type, fast_charging, city, service_history.
## For each column:
## • count unique categories
## • inspect frequencies
## • identify missing values
## • identify suspicious/inconsistent categories.

In [33]:
df.columns

Index(['vehicle_id', 'listing_date', 'manufacture_year', 'brand',
       'vehicle_type', 'battery_capacity_kwh', 'battery_health_pct',
       'range_km', 'km_driven', 'charging_time_hr', 'fast_charging',
       'owner_count', 'city', 'service_history', 'resale_price', 'vehicle_age',
       'km_per_year', 'charging_efficiency'],
      dtype='object')

In [39]:
df[['brand', 'vehicle_type', 'fast_charging', 'city', 'service_history']]

          brand vehicle_type fast_charging       city service_history
0        Nexora          SUV            No    Chennai        Complete
1        Nexora    Crossover            No    Chennai        Complete
2        Nexora    Crossover           Yes    Chennai        Complete
3    GreenDrive    Hatchback           Yes      Delhi        Complete
4    GreenDrive        Sedan            No       Pune        Complete
..          ...          ...           ...        ...             ...
995    E-Motion        Sedan            No  Bengaluru        Complete
996     Atheron    Hatchback           Yes  Bengaluru        Complete
997     Atheron    Crossover            No      Delhi         Partial
998  GreenDrive        Sedan           Yes    Chennai        Complete
999      Voltix    Crossover            No       Pune        Complete

[1000 rows x 5 columns]

In [42]:
for col in df:
    print("=" * 50)
    print("Column:", col)

    # Count unique categories
    print("Unique:", df[col].nunique())

    # Frequency of each category
    print("\nFrequencies:")
    print(df[col].value_counts(dropna=False))

    # Missing values
    print("\nMissing values:", df[col].isna().sum())

    # Unique values for inspection
    print("\nCatogaries:")
    print(df[col].unique())

==================================================
Column: vehicle_id
Unique: 994

Frequencies:
vehicle_id
EV-20193    2
EV-20544    2
EV-20515    2
EV-20011    2
EV-20653    2
           ..
EV-20153    1
EV-20868    1
EV-20353    1
EV-20886    1
EV-20168    1
Name: count, Length: 994, dtype: int64

Missing values: 0

Catogaries:
['EV-20170' 'EV-20530' 'EV-20654' 'EV-20935' 'EV-20827' 'EV-20547'
 'EV-20961' 'EV-20584' 'EV-20708' 'EV-20059' 'EV-20859' 'EV-20922'
 'EV-20381' 'EV-20023' 'EV-20541' 'EV-20445' 'EV-20256' 'EV-20236'
 'EV-20956' 'EV-20301' 'EV-20929' 'EV-20934' 'EV-20842' 'EV-20663'
 'EV-20501' 'EV-20421' 'EV-20208' 'EV-20085' 'EV-20997' 'EV-20349'
 'EV-20861' 'EV-20891' 'EV-20004' 'EV-20437' 'EV-20044' 'EV-20163'
 'EV-20497' 'EV-20969' 'EV-20848' 'EV-20903' 'EV-20674' 'EV-20056'
 'EV-20343' 'EV-20581' 'EV-20493' 'EV-20644' 'EV-20867' 'EV-20267'
 'EV-20252' 'EV-20767' 'EV-20986' 'EV-20007' 'EV-20560' 'EV-20074'
 'EV-20838' 'EV-20028' 'EV-20237' 'EV-20473' 'EV-20506' 'EV-20959'
 'EV-20980' 'EV-20577' 'EV-20552' 'EV-20782' 'EV-20753' 'EV-20356'
 'EV-20360' 'EV-20380' 'EV-20412' 'EV-20257' 'EV-20251' 'EV-20973'
 'EV-20515' 'EV-20713' 'EV-20392' 'EV-20874' 'EV-20078' 'EV-20049'
 'EV-20715' 'EV-20382' 'EV-20549' 'EV-20653' 'EV-20386' 'EV-20455'
 'EV-20238' 'EV-20175' 'EV-20285' 'EV-20622' 'EV-20955' 'EV-20452'
 'EV-20630' 'EV-20607' 'EV-20399' 'EV-20309' 'EV-20563' 'EV-20316'
 'EV-20142' 'EV-20384' 'EV-20254' 'EV-20488' 'EV-20606' 'EV-20276'
 'EV-20667' 'EV-20833' 'EV-20777' 'EV-20274' 'EV-20026' 'EV-20448'
 'EV-20938' 'EV-20122' 'EV-20507' 'EV-20873' 'EV-20203' 'EV-20524'
 'EV-20234' 'EV-20626' 'EV-20325' 'EV-20693' 'EV-20119' 'EV-20011'
 'EV-20832' 'EV-20977' 'EV-20318' 'EV-20288' 'EV-20598' 'EV-20926'
 'EV-20870' 'EV-20354' 'EV-20403' 'EV-20246' 'EV-20185' 'EV-20856'
 'EV-20932' 'EV-20544' 'EV-20646' 'EV-20865' 'EV-20845' 'EV-20499'
 'EV-20013' 'EV-20278' 'EV-20359' 'EV-20215' 'EV-20783' 'EV-20949'
 'EV-20114' 'EV-20282' 'EV-20365' 'EV-20420' 'EV-20292' 'EV-20127'
 'EV-20757' 'EV-20518' 'EV-20916' 'EV-20565' 'EV-20402' 'EV-20502'
 'EV-20051' 'EV-20751' 'EV-20140' 'EV-20247' 'EV-20662' 'EV-20456'
 'EV-20138' 'EV-20696' 'EV-20090' 'EV-20416' 'EV-20786' 'EV-20917'
 'EV-20103' 'EV-20083' 'EV-20352' 'EV-20655' 'EV-20183' 'EV-20459'
 'EV-20726' 'EV-20627' 'EV-20221' 'EV-20323' 'EV-20614' 'EV-20066'
 'EV-20091' 'EV-20190' 'EV-20465' 'EV-20789' 'EV-20562' 'EV-20355'
 'EV-20393' 'EV-20405' 'EV-20423' 'EV-20719' 'EV-20275' 'EV-20120'
 'EV-20330' 'EV-20561' 'EV-20480' 'EV-20554' 'EV-20920' 'EV-20553'
 'EV-20945' 'EV-20165' 'EV-20250' 'EV-20860' 'EV-20571' 'EV-20730'
 'EV-20564' 'EV-20855' 'EV-20609' 'EV-20006' 'EV-20557' 'EV-20613'
 'EV-20580' 'EV-20308' 'EV-20936' 'EV-20505' 'EV-20336' 'EV-20100'
 'EV-20024' 'EV-20152' 'EV-20625' 'EV-20483' 'EV-20729' 'EV-20391'
 'EV-20220' 'EV-20040' 'EV-20850' 'EV-20734' 'EV-20831' 'EV-20198'
 'EV-20720' 'EV-20749' 'EV-20202' 'EV-20419' 'EV-20228' 'EV-20639'
 'EV-20780' 'EV-20379' 'EV-20342' 'EV-20910' 'EV-20939' 'EV-20877'
 'EV-20123' 'EV-20081' 'EV-20807' 'EV-20339' 'EV-20242' 'EV-20645'
 'EV-20843' 'EV-20347' 'EV-20643' 'EV-20679' 'EV-20270' 'EV-20778'
 'EV-20370' 'EV-20464' 'EV-20048' 'EV-20583' 'EV-20803' 'EV-20908'
 'EV-20121' 'EV-20924' 'EV-20468' 'EV-20160' 'EV-20815' 'EV-20535'
 'EV-20657' 'EV-20439' 'EV-20612' 'EV-20551' 'EV-20229' 'EV-20597'
 'EV-20337' 'EV-20539' 'EV-20147' 'EV-20030' 'EV-20333' 'EV-20954'
 'EV-20451' 'EV-20187' 'EV-20272' 'EV-20897' 'EV-20450' 'EV-20050'
 'EV-20025' 'EV-20695' 'EV-20885' 'EV-20136' 'EV-20162' 'EV-20566'
 'EV-20517' 'EV-20314' 'EV-20440' 'EV-20839' 'EV-20640' 'EV-20364'
 'EV-20545' 'EV-20255' 'EV-20745' 'EV-20171' 'EV-20587' 'EV-20297'
 'EV-20741' 'EV-20390' 'EV-20476' 'EV-20230' 'EV-20377' 'EV-20133'
 'EV-20681' 'EV-20478' 'EV-20835' 'EV-20358' 'EV-20813' 'EV-20511'
 'EV-20003' 'EV-20268' 'EV-20635' 'EV-20523' 'EV-20179' 'EV-20491'
 'EV-20656' 'EV-20892' 'EV-20425' 'EV-20893' 'EV-20166' 'EV-20259'
 'EV-20043' 'EV-20883' 'EV-20871' 'EV-20520' 'EV-20596' 'EV-20134'
 'EV-20528' 'EV-20559' 'EV-20243' 'EV-20727' 'EV-20260' 'EV-20810'
 'EV-20398' 'EV-20155' 'EV-20153' 'EV-20868' 'EV-20353' 'EV-20886'
 'EV-20853' 'EV-20315' 'EV-20186' 'EV-20469' 'EV-20180' 'EV-20079'
 'EV-20490' 'EV-20537' 'EV-20249' 'EV-20407' 'EV-20145' 'EV-20383'
 'EV-20985' 'EV-20104' 'EV-20652' 'EV-20904' 'EV-20489' 'EV-20068'
 'EV-20054' 'EV-20854' 'EV-20306' 'EV-20691' 'EV-20516' 'EV-20351'
 'EV-20796' 'EV-20291' 'EV-20841' 'EV-20923' 'EV-20408' 'EV-20001'
 'EV-20486' 'EV-20484' 'EV-20115' 'EV-20295' 'EV-20241' 'EV-20245'
 'EV-20154' 'EV-20532' 'EV-20834' 'EV-20890' 'EV-20993' 'EV-20814'
 'EV-20825' 'EV-20058' 'EV-20071' 'EV-20572' 'EV-20300' 'EV-20404'
 'EV-20928' 'EV-20110' 'EV-20471' 'EV-20600' 'EV-20690' 'EV-20201'
 'EV-20307' 'EV-20701' 'EV-20304' 'EV-20101' 'EV-20015' 'EV-20424'
 'EV-20061' 'EV-20651' 'EV-20210' 'EV-20965' 'EV-20953' 'EV-20311'
 'EV-20338' 'EV-20601' 'EV-20107' 'EV-20620' 'EV-20146' 'EV-20041'
 'EV-20692' 'EV-20206' 'EV-20492' 'EV-20321' 'EV-20642' 'EV-20901'
 'EV-20957' 'EV-20919' 'EV-20366' 'EV-20895' 'EV-20664' 'EV-20800'
 'EV-20752' 'EV-20264' 'EV-20105' 'EV-20869' 'EV-20065' 'EV-20792'
 'EV-20941' 'EV-20704' 'EV-20269' 'EV-20900' 'EV-20611' 'EV-20389'
 'EV-20233' 'EV-20199' 'EV-20707' 'EV-20593' 'EV-20097' 'EV-20019'
 'EV-20682' 'EV-20648' 'EV-20931' 'EV-20589' 'EV-20921' 'EV-20029'
 'EV-20240' 'EV-20217' 'EV-20158' 'EV-20156' 'EV-20705' 'EV-20819'
 'EV-20109' 'EV-20703' 'EV-20453' 'EV-20371' 'EV-20616' 'EV-20536'
 'EV-20872' 'EV-20436' 'EV-20432' 'EV-20151' 'EV-20540' 'EV-20099'
 'EV-20660' 'EV-20556' 'EV-20947' 'EV-20617' 'EV-20852' 'EV-20676'
 'EV-20289' 'EV-20687' 'EV-20942' 'EV-20108' 'EV-20296' 'EV-20021'
 'EV-20846' 'EV-20460' 'EV-20888' 'EV-20636' 'EV-20332' 'EV-20709'
 'EV-20770' 'EV-20585' 'EV-20918' 'EV-20629' 'EV-20631' 'EV-20273'
 'EV-20435' 'EV-20599' 'EV-20057' 'EV-20650' 'EV-20430' 'EV-20685'
 'EV-20253' 'EV-20739' 'EV-20940' 'EV-20797' 'EV-20182' 'EV-20721'
 'EV-20735' 'EV-20579' 'EV-20413' 'EV-20913' 'EV-20974' 'EV-20239'
 'EV-20470' 'EV-20866' 'EV-20495' 'EV-20952' 'EV-20963' 'EV-20542'
 'EV-20927' 'EV-20878' 'EV-20879' 'EV-20176' 'EV-20864' 'EV-20668'
 'EV-20461' 'EV-20326' 'EV-20373' 'EV-20070' 'EV-20983' 'EV-20426'
 'EV-20340' 'EV-20418' 'EV-20042' 'EV-20284' 'EV-20335' 'EV-20063'
 'EV-20964' 'EV-20784' 'EV-20433' 'EV-20227' 'EV-20534' 'EV-20671'
 'EV-20008' 'EV-20293' 'EV-20623' 'EV-20271' 'EV-20746' 'EV-20930'
 'EV-20060' 'EV-20035' 'EV-20248' 'EV-20294' 'EV-20069' 'EV-20943'
 'EV-20851' 'EV-20303' 'EV-20084' 'EV-20798' 'EV-20688' 'EV-20226'
 'EV-20177' 'EV-20738' 'EV-20527' 'EV-20283' 'EV-20824' 'EV-20960'
 'EV-20262' 'EV-20225' 'EV-20658' 'EV-20950' 'EV-20967' 'EV-20388'
 'EV-20776' 'EV-20494' 'EV-20790' 'EV-20806' 'EV-20067' 'EV-20287'
 'EV-20966' 'EV-20331' 'EV-20857' 'EV-20533' 'EV-20526' 'EV-20998'
 'EV-20822' 'EV-20817' 'EV-20905' 'EV-20216' 'EV-20244' 'EV-20618'
 'EV-20387' 'EV-20801' 'EV-20894' 'EV-20647' 'EV-20764' 'EV-20409'
 'EV-20902' 'EV-20570' 'EV-20173' 'EV-20302' 'EV-20519' 'EV-20372'
 'EV-20876' 'EV-20576' 'EV-20706' 'EV-20118' 'EV-20529' 'EV-20987'
 'EV-20594' 'EV-20805' 'EV-20431' 'EV-20775' 'EV-20214' 'EV-20619'
 'EV-20169' 'EV-20191' 'EV-20829' 'EV-20362' 'EV-20862' 'EV-20479'
 'EV-20995' 'EV-20205' 'EV-20172' 'EV-20200' 'EV-20804' 'EV-20875'
 'EV-20548' 'EV-20821' 'EV-20991' 'EV-20794' 'EV-20196' 'EV-20700'
 'EV-20569' 'EV-20979' 'EV-20602' 'EV-20633' 'EV-20889' 'EV-20748'
 'EV-20263' 'EV-20376' 'EV-20590' 'EV-20909' 'EV-20787' 'EV-20808'
 'EV-20686' 'EV-20077' 'EV-20258' 'EV-20161' 'EV-20884' 'EV-20082'
 'EV-20128' 'EV-20774' 'EV-20802' 'EV-20317' 'EV-20578' 'EV-20193'
 'EV-20117' 'EV-20982' 'EV-20591' 'EV-20632' 'EV-20675' 'EV-20102'
 'EV-20188' 'EV-20689' 'EV-20045' 'EV-20781' 'EV-20002' 'EV-20972'
 'EV-20159' 'EV-20463' 'EV-20039' 'EV-20427' 'EV-20933' 'EV-20710'
 'EV-20098' 'EV-20911' 'EV-20699' 'EV-20733' 'EV-20280' 'EV-20582'
 'EV-20211' 'EV-20994' 'EV-20694' 'EV-20758' 'EV-20510' 'EV-20053'
 'EV-20369' 'EV-20441' 'EV-20742' 'EV-20038' 'EV-20588' 'EV-20150'
 'EV-20141' 'EV-20032' 'EV-20728' 'EV-20073' 'EV-20677' 'EV-20184'
 'EV-20672' 'EV-20684' 'EV-20462' 'EV-20385' 'EV-20946' 'EV-20673'
 'EV-20605' 'EV-20968' 'EV-20610' 'EV-20500' 'EV-20324' 'EV-20755'
 'EV-20725' 'EV-20990' 'EV-20126' 'EV-20970' 'EV-20785' 'EV-20396'
 'EV-20374' 'EV-20194' 'EV-20363' 'EV-20113' 'EV-20818' 'EV-20310'
 'EV-20521' 'EV-20608' 'EV-20788' 'EV-20849' 'EV-20106' 'EV-20621'
 'EV-20637' 'EV-20174' 'EV-20022' 'EV-20072' 'EV-20312' 'EV-20999'
 'EV-20971' 'EV-20092' 'EV-20089' 'EV-20178' 'EV-20678' 'EV-20907'
 'EV-20665' 'EV-20543' 'EV-20714' 'EV-20724' 'EV-20958' 'EV-20218'
 'EV-20779' 'EV-20504' 'EV-20555' 'EV-20112' 'EV-20088' 'EV-20638'
 'EV-20628' 'EV-20487' 'EV-20912' 'EV-20996' 'EV-20944' 'EV-20454'
 'EV-20368' 'EV-20266' 'EV-20086' 'EV-20231' 'EV-20036' 'EV-20649'
 'EV-20744' 'EV-20422' 'EV-20005' 'EV-20457' 'EV-20737' 'EV-20446'
 'EV-20830' 'EV-20816' 'EV-20429' 'EV-20219' 'EV-20467' 'EV-20447'
 'EV-20880' 'EV-20281' 'EV-20149' 'EV-20444' 'EV-20558' 'EV-20898'
 'EV-20716' 'EV-20148' 'EV-20514' 'EV-20449' 'EV-20313' 'EV-20680'
 'EV-20793' 'EV-20615' 'EV-20976' 'EV-20400' 'EV-20094' 'EV-20224'
 'EV-20634' 'EV-20261' 'EV-20736' 'EV-20322' 'EV-20509' 'EV-20474'
 'EV-20428' 'EV-20586' 'EV-20466' 'EV-20666' 'EV-20988' 'EV-20087'
 'EV-20144' 'EV-20906' 'EV-20345' 'EV-20477' 'EV-20812' 'EV-20761'
 'EV-20125' 'EV-20277' 'EV-20143' 'EV-20279' 'EV-20863' 'EV-20181'
 'EV-20017' 'EV-20232' 'EV-20702' 'EV-20047' 'EV-20157' 'EV-20740'
 'EV-20978' 'EV-20475' 'EV-20406' 'EV-20334' 'EV-20823' 'EV-20754'
 'EV-20027' 'EV-20414' 'EV-20164' 'EV-20760' 'EV-20442' 'EV-20212'
 'EV-20683' 'EV-20820' 'EV-20641' 'EV-20881' 'EV-20204' 'EV-20197'
 'EV-20139' 'EV-20722' 'EV-20791' 'EV-20661' 'EV-20573' 'EV-20209'
 'EV-20375' 'EV-20826' 'EV-20378' 'EV-20223' 'EV-20844' 'EV-20592'
 'EV-20298' 'EV-20009' 'EV-20327' 'EV-20840' 'EV-20207' 'EV-20915'
 'EV-20080' 'EV-20975' 'EV-20096' 'EV-20137' 'EV-20192' 'EV-20962'
 'EV-20052' 'EV-20020' 'EV-20458' 'EV-20443' 'EV-20743' 'EV-20064'
 'EV-20361' 'EV-20896' 'EV-20341' 'EV-20290' 'EV-20348' 'EV-20350'
 'EV-20319' 'EV-20222' 'EV-20411' 'EV-20131' 'EV-20604' 'EV-20718'
 'EV-20847' 'EV-20697' 'EV-20018' 'EV-20346' 'EV-20574' 'EV-20731'
 'EV-20567' 'EV-20698' 'EV-20669' 'EV-20503' 'EV-20769' 'EV-20951'
 'EV-20046' 'EV-20989' 'EV-20981' 'EV-20031' 'EV-20836' 'EV-20265'
 'EV-20659' 'EV-20858' 'EV-20732' 'EV-20093' 'EV-20508' 'EV-20546'
 'EV-20773' 'EV-20759' 'EV-20498' 'EV-20496' 'EV-20095' 'EV-20837'
 'EV-20568' 'EV-20766' 'EV-20828' 'EV-20329' 'EV-20531' 'EV-20000'
 'EV-20195' 'EV-20076' 'EV-20472' 'EV-20130' 'EV-20624' 'EV-20111'
 'EV-20747' 'EV-20717' 'EV-20305' 'EV-20550' 'EV-20992' 'EV-20482'
 'EV-20320' 'EV-20033' 'EV-20135' 'EV-20344' 'EV-20763' 'EV-20010'
 'EV-20395' 'EV-20768' 'EV-20711' 'EV-20037' 'EV-20397' 'EV-20811'
 'EV-20132' 'EV-20603' 'EV-20286' 'EV-20167' 'EV-20723' 'EV-20575'
 'EV-20016' 'EV-20899' 'EV-20367' 'EV-20762' 'EV-20948' 'EV-20075'
 'EV-20772' 'EV-20750' 'EV-20512' 'EV-20417' 'EV-20513' 'EV-20522'
 'EV-20925' 'EV-20882' 'EV-20235' 'EV-20014' 'EV-20765' 'EV-20481'
 'EV-20670' 'EV-20012' 'EV-20434' 'EV-20937' 'EV-20771' 'EV-20914'
 'EV-20034' 'EV-20055' 'EV-20887' 'EV-20485' 'EV-20394' 'EV-20415'
 'EV-20062' 'EV-20438' 'EV-20299' 'EV-20525' 'EV-20189' 'EV-20116'
 'EV-20795' 'EV-20129' 'EV-20213' 'EV-20595' 'EV-20328' 'EV-20357'
 'EV-20756' 'EV-20984' 'EV-20410' 'EV-20168']
==================================================
Column: listing_date
Unique: 1000

Frequencies:
listing_date
2025-01-01    1
2026-11-03    1
2026-10-21    1
2026-10-22    1
2026-10-23    1
             ..
2025-12-05    1
2025-12-06    1
2025-12-07    1
2025-12-08    1
2027-09-27    1
Name: count, Length: 1000, dtype: int64

Missing values: 0

Catogaries:
<DatetimeArray>
['2025-01-01 00:00:00', '2025-01-02 00:00:00', '2025-01-03 00:00:00',
 '2025-01-04 00:00:00', '2025-01-05 00:00:00', '2025-01-06 00:00:00',
 '2025-01-07 00:00:00', '2025-01-08 00:00:00', '2025-01-09 00:00:00',
 '2025-01-10 00:00:00',
 ...
 '2027-09-18 00:00:00', '2027-09-19 00:00:00', '2027-09-20 00:00:00',
 '2027-09-21 00:00:00', '2027-09-22 00:00:00', '2027-09-23 00:00:00',
 '2027-09-24 00:00:00', '2027-09-25 00:00:00', '2027-09-26 00:00:00',
 '2027-09-27 00:00:00']
Length: 1000, dtype: datetime64[ns]
==================================================
Column: manufacture_year
Unique: 10

Frequencies:
manufacture_year
2023    118
2019    111
2016    104
2017    103
2020    102
2022     96
2021     95
2025     94
2024     93
2018     84
Name: count, dtype: int64

Missing values: 0

Catogaries:
[2021 2025 2019 2022 2024 2017 2023 2020 2016 2018]
==================================================
Column: brand
Unique: 5

Frequencies:
brand
Nexora        213
Atheron       207
GreenDrive    196
E-Motion      192
Voltix        192
Name: count, dtype: int64

Missing values: 0

Catogaries:
['Nexora' 'GreenDrive' 'Atheron' 'E-Motion' 'Voltix']
==================================================
Column: vehicle_type
Unique: 4

Frequencies:
vehicle_type
SUV          265
Hatchback    251
Crossover    244
Sedan        240
Name: count, dtype: int64

Missing values: 0

Catogaries:
['SUV' 'Crossover' 'Hatchback' 'Sedan']
==================================================
Column: battery_capacity_kwh
Unique: 459

Frequencies:
battery_capacity_kwh
NaN     25
62.4     9
61.9     7
25.0     6
58.7     6
        ..
52.7     1
39.4     1
33.5     1
91.7     1
91.1     1
Name: count, Length: 460, dtype: int64

Missing values: 25

Catogaries:
[ 46.9         80.6         53.9         60.1         53.
  44.1         34.9         41.6         51.9         65.2
  74.4         59.          60.9                 nan  60.6
  61.2         52.9         74.6         61.3         53.1
  79.7         26.9         50.1         48.1         56.2
  58.9         37.1         96.5         54.6         73.5
  61.5         28.7         53.7         66.7         63.1
  49.6         55.8         25.          59.6         86.3
  73.1         62.4         70.5         53.3         37.5
  71.2         62.2         48.5         78.5         61.
  54.3         50.6         77.3         44.4         86.7
  49.9         55.3         75.5         49.3         49.8
  78.3         81.3         47.9         47.6         57.
  69.9         35.8         33.4         51.6         61.6
  32.7         57.3         63.5         48.2         75.9
  52.3         61.1         61.4         47.1         69.8
  73.3         54.9         81.6         78.1         35.
  81.9         71.5         75.3         33.7         72.6
  50.7         53.5         68.9         63.7         79.4
  67.6         89.9         46.1         68.7         47.5
  83.5         34.2         52.          62.5         70.7
  76.8         75.2         62.1         57.9         48.9
  65.4         55.9         67.3         65.8         56.4
  50.9         40.4         70.8         58.7         69.1
  46.7         60.3         38.          49.2         51.4
  63.6         52.4         29.6         71.9         71.8
  64.4         49.          68.1         80.8         61.7
  40.2         81.5         45.9         83.2         83.6
  77.         100.          63.2         79.3         94.2
  43.7         50.8         85.7         54.          67.7
  66.4         54.1         58.6         54.5         42.5
  55.2         71.4         72.2         51.3         57.1
  90.6         39.6         66.3         28.6         67.5
  84.          39.7         39.9         35.1         48.3
  51.2         70.9         57.7         34.3         45.2
  44.9         51.1         42.6         46.6         58.3
  68.5         41.9         74.3         29.9         81.4
  25.5         66.6         46.2         69.4         74.1
  83.9         59.4         56.5         39.3         76.1
  66.          89.          61.9         83.          53.8
  72.5         67.8         50.3         47.8         67.9
  56.9         38.9         47.4         44.8         59.2
  76.4         42.9         43.6         41.5         85.3
  58.2         64.3         62.9         75.6         64.5
  57.5         65.5         47.          46.3         49.1
  63.4         56.          36.6         33.          66.9
  44.3         52.5         62.6         45.1         82.2
  51.          37.6         74.9         41.4         42.4
  79.          64.1         57.2         47.7         69.
  64.7         77.90746881  52.2         32.5         51.5
  25.7         43.5         69.3         80.7         36.4
  77.1         37.3         87.6         37.7         52.1
  58.1         38.4         77.6         62.7         33.2
  57.6         67.4         45.3         48.7         43.9
  52.7         65.7         39.4         82.8         33.5
  91.7         41.7         70.4         62.          60.8
  51.8         73.6         37.9         65.3         65.
  83.3         57.4         88.6         72.7         45.4
  49.4         42.          73.8         59.8         61.8
  44.          43.1         58.5         54.4         87.9
  41.8         59.7         70.1         59.9         62.8
  58.8         41.2         65.9         32.1         55.5
  64.9         73.7         88.4         78.4         52.8
  76.5         47.2         72.          48.4         39.1
  26.3         36.3         91.4         54.7         55.6
  45.5         45.8         46.8         38.2         72.1
  34.7         60.          40.9         72.8         50.5
  52.6         63.9         67.1        110.4059804   80.1
  36.5         56.6         58.          63.3         53.2
  95.3         43.8         44.5         69.2         30.
  76.7         75.7         41.1         93.19228224  45.7
  45.6         30.8         79.8         86.2         49.5
  70.          66.5         68.4         80.          45.83600478
  55.          37.4         31.          92.6         47.3
 105.0572304   31.3         32.9         35.4        109.2030823
  69.7         44.6         50.          38.1         66.8
  55.4         54.8         84.9         87.7         60.4
  39.          60.2         51.7         29.5         59.3
  64.2         43.          34.6         79.2         50.2
  71.1         31.8         42.3         59.1         84.8
  49.7         68.3         64.          55.1         68.2
  61.41577406  66.1         60.5         53.4         78.7
  35.9         60.7         68.          55.7         69.6
  46.          36.2         42.2         65.6         56.7
  34.5         79.5         56.3         97.1         78.8
  71.3         29.7         41.3         69.5         30.9
  78.6         43.4         70.6         46.4         80.5
  70.2         32.6         76.6         79.9         73.2
  66.2         97.7         74.7         91.9         82.5
  62.3         92.4         64.8         39.5         68.8
  75.4         43.2         73.          35.3         78.11816494
  56.1         48.          38.6         65.1         91.1       ]
==================================================
Column: battery_health_pct
Unique: 197

Frequencies:
battery_health_pct
100.0    40
NaN      30
91.2     13
92.8     12
87.8     11
         ..
83.2      1
78.7      1
79.8      1
84.4      1
99.9      1
Name: count, Length: 198, dtype: int64

Missing values: 30

Catogaries:
[ 89.6  99.5  91.2  89.3  92.   89.9  95.1  92.6  89.7  90.2  89.4  91.6
 100.   83.2  90.4  96.   94.   95.4  93.6  84.9  93.7  94.3  86.3  91.3
  89.1  85.1  96.9  87.8  93.8   nan  85.6  83.1  95.7  88.7  94.7  91.9
  86.2  97.4  79.8  98.4  82.6  93.5  93.   95.5  98.   90.8  98.6  90.7
  94.9  94.8  93.2  90.9  96.4  89.5  85.7  91.8  78.9  92.3  92.4  89.
  81.7  96.8  86.7  91.   91.7  93.3  90.   98.8  99.3  84.6  97.7  92.8
  90.5  88.5  97.5  88.   95.9  99.7  85.   78.6  89.8  96.7  85.5  98.2
  96.1  92.1  90.3  85.3  93.9  77.   96.5  97.9  85.4  88.6  94.1  98.5
  84.   95.   87.7  95.8  88.4  88.3  90.1  90.6  92.5  83.7  97.8  96.6

## 12. Service History Cleaning
## service_history contains Complete, Partial, Missing, and NaN.
## Determine whether “Missing” and actual NaN represent the same business meaning.
## Then create a consistent representation suitable for ML.

In [44]:
import numpy as np

df['service_history'] = df['service_history'].replace('Missing', np.nan)

In [45]:
df['service_history'].value_counts(dropna=False)

service_history
Complete    590
Partial     297
NaN         113
Name: count, dtype: int64

In [48]:
df['service_history_ml'] = df['service_history'].fillna('Unknown')
df.head(2)

,vehicle_id,listing_date,manufacture_year,brand,vehicle_type,battery_capacity_kwh,battery_health_pct,range_km,km_driven,charging_time_hr,fast_charging,owner_count,city,service_history,resale_price,vehicle_age,km_per_year,charging_efficiency,service_history_ml
0,EV-20170,2025-01-01,2021,Nexora,SUV,46.9,89.6,313.0,28454.0000,10.0,No,1,Chennai,Complete,1527836,5,5690.8000,31.300000,Complete
1,EV-20530,2025-01-02,2025,Nexora,Crossover,80.6,99.5,543.0,183935.8448,7.1,No,2,Chennai,Complete,2040760,1,183935.8448,76.478873,Complete

In [49]:
df['service_history_ml'].value_counts()

service_history_ml
Complete    590
Partial     297
Unknown     113
Name: count, dtype: int64

## 13. Fast Charging Transformation
## Transform fast_charging from Yes / No into a binary numerical representation.
## Verify the transformation using frequency counts before and after.

In [50]:
df['fast_charging'].value_counts(dropna=False)

fast_charging
Yes    692
No     308
Name: count, dtype: int64

In [53]:
df['fast_charging'] = df['fast_charging'].replace({
    'Yes': 1,
    'No': 0
})

In [55]:
df['fast_charging'].value_counts(dropna=False)

fast_charging
1    692
0    308
Name: count, dtype: int64

## 14. Target Analysis
## Analyze resale_price.
## Calculate and inspect:
## • mean
## • median
## • minimum
## • maximum
## • standard deviation
## • potential extreme values
## Determine whether the target contains suspicious observations that could strongly influence a regression model.

In [56]:
print("Mean:", df['resale_price'].mean())
print("Median:", df['resale_price'].median())
print("Minimum:", df['resale_price'].min())
print("Maximum:", df['resale_price'].max())
print("Standard Deviation:", df['resale_price'].std())

Mean: 1586535.101
Median: 1589594.0
Minimum: 915109
Maximum: 2072547
Standard Deviation: 166204.3759912459

In [57]:
Q1 = df['resale_price'].quantile(0.25)
Q3 = df['resale_price'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

extreme_values = df[
    (df['resale_price'] < lower_limit) |
    (df['resale_price'] > upper_limit)
]

extreme_values[['vehicle_id', 'resale_price']]

    vehicle_id  resale_price
1     EV-20530       2040760
135   EV-20865       1117512
213   EV-20505       1047190
218   EV-20625       1011244
234   EV-20780        915109
597   EV-20173       2029110
665   EV-20781       2042543
786   EV-20313       1019997
873   EV-20743       2072547
963   EV-20513       1140605

In [58]:
print("Number of extreme values:", len(extreme_values))

Number of extreme values: 10

## 15. Price-per-Kilometer Feature
## Create price_per_km using:
## resale_price / km_driven
## Investigate whether extremely low/high values are caused by very low mileage, very high price, or data-quality
## problems.

In [59]:
import numpy as np

df['price_per_km'] = (
    df['resale_price'] / df['km_driven'].replace(0, np.nan)
)

df[['vehicle_id', 'resale_price', 'km_driven', 'price_per_km']]

    vehicle_id  resale_price    km_driven  price_per_km
0     EV-20170       1527836   28454.0000     53.694946
1     EV-20530       2040760  183935.8448     11.094955
2     EV-20654       1830249   12003.0000    152.482629
3     EV-20935       1726422   13623.0000    126.728474
4     EV-20827       1642232   28548.0000     57.525291
..         ...           ...          ...           ...
995   EV-20357       1338124   61861.0000     21.631141
996   EV-20756       1624596   55605.0000     29.216725
997   EV-20984       1958519   23708.0000     82.610047
998   EV-20410       1724555   39435.0000     43.731584
999   EV-20168       1232571  103173.0000     11.946643

[1000 rows x 4 columns]

In [60]:
Q1 = df['price_per_km'].quantile(0.25)
Q3 = df['price_per_km'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

extreme_values = df[
    (df['price_per_km'] < lower_limit) |
    (df['price_per_km'] > upper_limit)
]

extreme_values[
    ['vehicle_id', 'resale_price', 'km_driven', 'price_per_km']
]

    vehicle_id  resale_price  km_driven  price_per_km
2     EV-20654       1830249    12003.0    152.482629
3     EV-20935       1726422    13623.0    126.728474
6     EV-20961       1605157    11615.0    138.196901
7     EV-20584       1589566     6999.0    227.113302
14    EV-20541       1889781    11531.0    163.887000
39    EV-20903       1939616    14228.0    136.323868
84    EV-20238       1886520    13442.0    140.345187
88    EV-20955       1726590     8232.0    209.741254
91    EV-20607       1856159    13806.0    134.445821
98    EV-20254       1693139    13154.0    128.716664
99    EV-20488       1605711     6812.0    235.717998
104   EV-20777       1578645     9901.0    159.442986
106   EV-20026       1821676    14546.0    125.235529
156   EV-20051       1736790    10698.0    162.347168
169   EV-20083       1696722    12642.0    134.213099
183   EV-20789       1684025     9498.0    177.303116
186   EV-20393       1846703    12977.0    142.305849
226   EV-20831       1602836    10518.0    152.389808
236   EV-20342       1645310    13577.0    121.183619
242   EV-20807       1859545    12495.0    148.823129
271   EV-20539       1723377    14152.0    121.776215
316   EV-20523       1613259     7881.0    204.702322
360   EV-20068       1518841    10579.0    143.571321
362   EV-20854       1866808     6845.0    272.725785
364   EV-20691       1485297    11105.0    133.750293
392   EV-20110       1514054    10404.0    145.526144
407   EV-20953       1575666    11613.0    135.681219
431   EV-20065       1706521    12049.0    141.631754
510   EV-20239       1738157     9731.0    178.620594
513   EV-20495       1792527     8878.0    201.906623
585   EV-20905       1584806     6965.0    227.538550
597   EV-20173       2029110    14720.0    137.847147
615   EV-20829       1684990    10596.0    159.021329
624   EV-20804       1586813     6086.0    260.731679
629   EV-20794       1653340    11193.0    147.711963
637   EV-20748       1519483    11329.0    134.123312
638   EV-20263       1787362    13127.0    136.159214
694   EV-20728       1692929    12431.0    136.186067
702   EV-20946       1981109     8045.0    246.253449
718   EV-20363       1744557    13853.0    125.933516
753   EV-20487       1715613     5779.0    296.870220
763   EV-20649       1803188    10077.0    178.940955
774   EV-20467       1858455    14083.0    131.964425
785   EV-20449       1796592    13318.0    134.899534
787   EV-20680       1627888    12863.0    126.555858
832   EV-20414       1826602     6719.0    271.856229
839   EV-20641       1675031    13121.0    127.660316
842   EV-20197       1873996     8368.0    223.947897
878   EV-20290       1614795     8239.0    195.994053
950   EV-20167       1664788    10856.0    153.351879
992   EV-20213       1633608     9262.0    176.377456

In [61]:
extreme_values[
    ['vehicle_id', 'resale_price', 'km_driven', 'price_per_km']
].sort_values('price_per_km')

    vehicle_id  resale_price  km_driven  price_per_km
236   EV-20342       1645310    13577.0    121.183619
271   EV-20539       1723377    14152.0    121.776215
106   EV-20026       1821676    14546.0    125.235529
718   EV-20363       1744557    13853.0    125.933516
787   EV-20680       1627888    12863.0    126.555858
3     EV-20935       1726422    13623.0    126.728474
839   EV-20641       1675031    13121.0    127.660316
98    EV-20254       1693139    13154.0    128.716664
774   EV-20467       1858455    14083.0    131.964425
364   EV-20691       1485297    11105.0    133.750293
637   EV-20748       1519483    11329.0    134.123312
169   EV-20083       1696722    12642.0    134.213099
91    EV-20607       1856159    13806.0    134.445821
785   EV-20449       1796592    13318.0    134.899534
407   EV-20953       1575666    11613.0    135.681219
638   EV-20263       1787362    13127.0    136.159214
694   EV-20728       1692929    12431.0    136.186067
39    EV-20903       1939616    14228.0    136.323868
597   EV-20173       2029110    14720.0    137.847147
6     EV-20961       1605157    11615.0    138.196901
84    EV-20238       1886520    13442.0    140.345187
431   EV-20065       1706521    12049.0    141.631754
186   EV-20393       1846703    12977.0    142.305849
360   EV-20068       1518841    10579.0    143.571321
392   EV-20110       1514054    10404.0    145.526144
629   EV-20794       1653340    11193.0    147.711963
242   EV-20807       1859545    12495.0    148.823129
226   EV-20831       1602836    10518.0    152.389808
2     EV-20654       1830249    12003.0    152.482629
950   EV-20167       1664788    10856.0    153.351879
615   EV-20829       1684990    10596.0    159.021329
104   EV-20777       1578645     9901.0    159.442986
156   EV-20051       1736790    10698.0    162.347168
14    EV-20541       1889781    11531.0    163.887000
992   EV-20213       1633608     9262.0    176.377456
183   EV-20789       1684025     9498.0    177.303116
510   EV-20239       1738157     9731.0    178.620594
763   EV-20649       1803188    10077.0    178.940955
878   EV-20290       1614795     8239.0    195.994053
513   EV-20495       1792527     8878.0    201.906623
316   EV-20523       1613259     7881.0    204.702322
88    EV-20955       1726590     8232.0    209.741254
842   EV-20197       1873996     8368.0    223.947897
7     EV-20584       1589566     6999.0    227.113302
585   EV-20905       1584806     6965.0    227.538550
99    EV-20488       1605711     6812.0    235.717998
702   EV-20946       1981109     8045.0    246.253449
624   EV-20804       1586813     6086.0    260.731679
832   EV-20414       1826602     6719.0    271.856229
362   EV-20854       1866808     6845.0    272.725785
753   EV-20487       1715613     5779.0    296.870220

In [62]:
df[df['km_driven'] <= 1000][
    ['vehicle_id', 'resale_price', 'km_driven', 'price_per_km']
]

Empty DataFrame
Columns: [vehicle_id, resale_price, km_driven, price_per_km]
Index: []

## 16. Battery Health × Usage Feature
## Create a combined feature called battery_usage_index based on battery_health_pct and km_driven.
## Design a meaningful formula and explain why this feature could help predict resale price.

In [64]:
df['battery_usage_index'] = (
    df['km_driven'] * (100 - df['battery_health_pct'])
)
df[['battery_health_pct', 'km_driven', 'battery_usage_index']]

     battery_health_pct    km_driven  battery_usage_index
0                  89.6   28454.0000         2.959216e+05
1                  99.5  183935.8448         9.196792e+04
2                  91.2   12003.0000         1.056264e+05
3                  89.3   13623.0000         1.457661e+05
4                  92.0   28548.0000         2.283840e+05
..                  ...          ...                  ...
995                89.9   61861.0000         6.247961e+05
996                99.9   55605.0000         5.560500e+03
997                81.8   23708.0000         4.314856e+05
998                98.6   39435.0000         5.520900e+04
999                88.2  103173.0000         1.217441e+06

[1000 rows x 3 columns]

In [65]:
df['battery_usage_index'].describe()

count    9.700000e+02
mean     4.696784e+05
std      4.730818e+05
min      0.000000e+00
25%      1.659815e+05
50%      3.337226e+05
75%      6.112404e+05
max      3.636000e+06
Name: battery_usage_index, dtype: float64