# Pandas Method Task: Bank Customer Churn Dataset

In [36]:
# 1. Load the dataset using the appropriate Pandas method and store it in a variable named df.
import pandas as pd
df = pd.read_csv("C:\\Users\\MY PC\\OneDrive\\Desktop\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [13]:
# 2. Display the first 8 rows of the dataset.
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [14]:
# 3. Display the last 12 rows of the dataset.
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [19]:
# 4. Show 10 random rows from the dataset.
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5480,5481,15659094,Ojiofor,765,Germany,Female,34,8,136729.51,2,0,0,47058.21,0
4498,4499,15777759,Boucaut,570,France,Male,30,2,131406.56,1,1,1,47952.45,0
5764,5765,15791851,Afanasyeva,726,France,Female,34,0,185734.75,1,1,1,102036.82,0
721,722,15578761,Cunningham,459,Spain,Female,42,6,129634.25,2,1,1,177683.02,1
3521,3522,15812706,Mazure,627,Spain,Male,49,4,111087.50,1,0,1,146680.25,0
6866,6867,15664506,Goodwin,675,Spain,Male,32,8,197436.82,1,1,1,52710.70,0
2551,2552,15631310,Hsieh,537,France,Female,53,3,0.00,1,1,1,91406.62,0
5842,5843,15799128,Matthews,608,Spain,Female,38,9,102406.76,1,0,1,57600.66,0
1431,1432,15809772,Glover,667,France,Male,48,2,0.00,1,1,0,43229.20,0
499,500,15677020,Selezneva,570,France,Female,58,8,0.00,1,0,1,116503.92,1

In [22]:
# 5. Find the shape of the dataset.
# o How many rows are there?
# o How many columns are there?
df.shape

(10000, 14)

In [23]:
# 6. Display complete information about the dataset using one method.
# o Number of non-null values
# o Data types
# o Memory usage 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [24]:
# 7. Print the names of all columns in the dataset.
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [27]:
# 8. Find the data type of every column.
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [28]:
# 9. Check for missing values in every column using:
# o isnull().sum()
# o isna().sum()

df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [29]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [32]:
# 10.Select only one column:
# o CreditScore
df["CreditScore"].value_counts(dropna = True)

CreditScore
850    233
678     63
655     54
705     53
667     53
      ...
404      1
351      1
365      1
417      1
419      1
Name: count, Length: 460, dtype: int64

In [37]:
# 11.Select the following multiple columns:
# o CustomerId
# o Surname
# o Balance
# o Exited
multi = df[["CustomerId","Surname","Balance","Exited"]]
multi

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

In [6]:
import pandas as pd
df = pd.read_csv("C:\\Users\\MY PC\\OneDrive\\Desktop\\Bank_customer_churn.csv")

In [7]:
# 12.Display only numeric columns using select_dtypes().
df.select_dtypes(include=["int","float"]).columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [8]:
# 13.Generate the statistical summary of all numeric columns using describe().
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [15]:
# 14.Check for duplicate rows in the dataset.
# o How many duplicate rows exist?
# o Remove all duplicate rows.
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [18]:
df.drop_duplicates(inplace=True)

In [14]:
# 15.Count the number of customers in each class of the Exited column using  value_counts().
df.value_counts()

RowNumber  CustomerId  Surname     CreditScore  Geography  Gender  Age  Tenure  Balance    NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
1          15634602    Hargrave    619          France     Female  42   2       0.00       1              1          1               101348.88        1         1
6671       15667932    Bellucci    758          Spain      Female  43   10      0.00       2              1          1               55313.44         0         1
6664       15766185    She         850          Germany    Male    31   4       146587.30  1              1          1               89874.82         0         1
6665       15667632    Birdseye    703          France     Female  42   7       0.00       2              0          1               72500.68         0         1
6666       15599024    Hope        506          Spain      Male    32   8       0.00       2              0          1               182692.80        0         1
                                                                                                                                                               ..
3334       15599078    Yang        619          Germany    Female  41   5       92467.58   1              1          0               38270.47         0         1
3335       15702300    Walker      671          France     Male    27   5       0.00       2              0          0               120893.07        0         1
3336       15660735    T'ang       581          Spain      Female  31   6       0.00       2              1          0               188377.21        0         1
3337       15671390    Chukwukere  690          Spain      Male    36   10      0.00       2              1          0               55902.93         0         1
10000      15628319    Walker      792          France     Female  28   4       130142.79  1              1          0               38190.78         0         1
Name: count, Length: 10000, dtype: int64

# Operators + Loops (1-5)

In [17]:
# 1. Take two numbers from user. Perform all arithmetic operations and also check which number is greater using comparison operators.
A =int(input("please enter a num"))
B =float(input("please enter a num"))
print("addition :",A + B)
print("subtraction :",A - B)
print("multiplication :",A % B)
print("division :",A / B)
if A > B:
    print("A is greater than B")
elif A < B:
    print("B is greater than A")
else:
    print("both are equall")

please enter a num 5
please enter a num 4

addition : 9.0
subtraction : 1.0
multiplication : 1.0
division : 1.25
A is greater than B

In [16]:
# 2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop completely when number 40 is reached using break.
for i in range(1,51):
    if i == 40:
        
        break

    if i % 5 == 0:
        continue

    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39

In [20]:
# 3. Take numbers from user until they enter negative number. Calculate sum and average using while loop.
total = 0
count = 0

while True:
    num =int(input("please enter a number"))
    if num < 0:
        break

    total += num
    count += 1

if count > 0:
    average = total / count
    print("sum:",total)
    print("average",average)
else:
    print("It a Negative number")

please enter a number 5
please enter a number 2
please enter a number -4

sum: 7
average 3.5

In [15]:
# 4. Print the following pattern using nested loops:
for i in range(5,0,-1):
    for j in range(i):
        print("*",end=" ")
    print()

* * * * *
* * * *
* * *
* *
*

In [4]:
# 5. Find the factorial of a number using for loop and also using while loop.
num =int(input("enter the num:"))
fact = 1
i = 1

while i <= num:
    fact *= i
    i += 1

    
print("factorial:",fact)

enter the num: 5

factorial: 120

# Data Types & Methods (6-9)

In [8]:
# 6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace spaces with -, and check if it starts with “Hello”.
name = "Hello tHis iS python ProgaMM"
print(name.upper())
print(name.count("a"))
print(name.replace("a","--"))
print(name.startswith("Hello"))

HELLO THIS IS PYTHON PROGAMM
1
Hello tHis iS python Prog--MM
True

In [26]:
#7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending) and reverse.
A = [1,2,3,4,5,6]

A.append(7)
print(A)

A.insert(2,8)
print(A)

A.remove(5)
print(A)

A.pop(6)
print(A)

A.sort()
print(A)

A.reverse()
print(A)

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 8, 3, 4, 5, 6, 7]
[1, 2, 8, 3, 4, 6, 7]
[1, 2, 8, 3, 4, 6]
[1, 2, 3, 4, 6, 8]
[8, 6, 4, 3, 2, 1]

In [44]:
# 8. Create a dictionary of 4 students (name:marks). Print only those students who scored more than 80 using items().
Students = {  "santosh" :85,
              "paritosh":15,
              "yash" :99,
              "anil" :91,     
}
for name ,marks in Students.items():
    if marks > 80:
        print(name,":",marks)

santosh : 85
yash : 99
anil : 91

In [50]:
# 9. Create two sets and perform union, intersection, difference. Also add and discard elements.
set1 = {10,20,30,40,50}
set2 = {70,80,90,20,60}

print(set1)
print(set2)

print(set1.union(set2))

print(set1.intersection(set2))

print(set1.difference(set2))
print(set2.difference(set1))
set1.add(55)
print(set1)

set1.discard(40)
print(set1)

{50, 20, 40, 10, 30}
{80, 20, 70, 90, 60}
{70, 40, 10, 80, 50, 20, 90, 60, 30}
{20}
{40, 50, 10, 30}
{80, 90, 60, 70}
{50, 20, 55, 40, 10, 30}
{50, 20, 55, 10, 30}

# OOP + Encapsulation (10-14)

In [19]:
# 10. Create a class Student with private attribute __marks. Add getter and setter with validation (0–100).
class Student:
    def __init__(self, marks):
        self.__marks = marks

    # Getter
    def get_marks(self):
        return self.__marks

    # Setter
    def set_marks(self, marks):
        if 0 <= marks <= 100:
            self.__marks = marks
            print("Marks updated")
        else:
            print("Invalid marks")

student = Student(85)

print("Current Marks:",student.get_marks())

student.set_marks(95)
print("Updated Marks:",student.get_marks())

Current Marks: 85
Marks updated
Updated Marks: 95

In [30]:
# 11. Create class BankAccount with private __balance. Add deposit and withdraw
# methods. Raise custom exception if balance becomes negative.    
class BankAccount:
    def __init__(self,balance):
        self.__balance = balance

    def deposit(self,amount):
        self.__balance += amount
        print("amount deposited :",amount)

    def withdraw(self,amount):
        if  self.__balance - amount < 0:
            raise InsufficientBalanceError("insufficient balance")
        else:
            self.__balance -= amount
            print("amount withdrawn",amount)

    def get_balance(self):
        return self.__balance

account = BankAccount(5000)

print("Balance :",account.get_balance())

account.deposit(7000)
print("Deposit :",account.get_balance())

try:
    account.withdraw(7000)
except InsufficientBalanceError as e:
    print(e)

print("Balance:", account.get_balance())

Balance : 5000
amount deposited : 7000
Deposit : 12000
amount withdrawn 7000
Balance: 5000

In [34]:
# 12. Create class Employee with class attribute company_name. Show that it is
# shared by all objects. Also update the class attribute.
class Employee:
    company_name = "paritosh Tech"  # class attri

    def __init__(self,name):
        self.name = name

emp1 = Employee("Santosh")
emp2 = Employee("Rahul")

print(emp1.name, "-",emp1.company_name)
print(emp2.name, "-",emp2.company_name)

Employee.company_name = "ABC Solutions"

print("\nAfter update company name:")
print(emp1.name, "-",emp1.company_name)
print(emp2.name, "-",emp2.company_name)

Santosh - paritosh Tech
Rahul - paritosh Tech

After update company name:
Santosh - ABC Solutions
Rahul - ABC Solutions

In [42]:
# 13. Create class Product with private __price. Add getter and setter. Setter should
 # not allow price less than 100.
class Product:
    def __init__(self,price):
        self.__price = price

    def get_Product(self):
        return self.__price

    def set_Product(self,price):
        if price < 100:
            print("amount should be more than 100")
        else:
            self.__price = price
            print("amount updated")

items = Product(101)

print("current price:",items.get_Product())

items.set_Product(124)
print("updated price:",items.get_Product())

items.set_Product(99)
print(items.get_Product())

current price: 101
amount updated
updated price: 124
amount should be more than 100
124

In [48]:
# 14. Create class Rectangle with private length and width. Add method to calculate
# area and perimeter.
class Rectangle:
    def __init__(self,length,width):
        self.__length = length
        self.__width = width

    def area(self):
        return  self.__length * self.__width

    def perimeter(self):
        return 2 *( self.__length + self.__width )

        print("area:",area)
        print("perimeter:",perimeter)

ret = Rectangle(5,2)
print(ret.area())
print(ret.perimeter())

10
14